"""initial schema

Revision ID: a71ea9d19503
Revises:
Create Date: 2026-07-01 21:10:18.218348
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a71ea9d19503"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_group",
        sa.Column("allowed_groups", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("allowed_domains", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reconcile_failures", sa.Integer(), nullable=False),
        sa.Column("reconcile_last_error", sa.Text(), nullable=True),
        sa.Column("reconcile_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("name"),
        schema="first",
    )
    op.create_table(
        "cluster",
        sa.Column("status_method", sa.String(), nullable=False),
        sa.Column(
            "status_kwargs", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("maintenance_notice", sa.String(), nullable=True),
        sa.Column(
            "pilot_system", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("last_status_check", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reconcile_failures", sa.Integer(), nullable=False),
        sa.Column("reconcile_last_error", sa.Text(), nullable=True),
        sa.Column("reconcile_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("name"),
        schema="first",
    )
    op.create_table(
        "config_version",
        sa.Column(
            "applied_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("applied_by", sa.String(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
        schema="first",
    )
    op.create_table(
        "controller_manager_lease",
        sa.Column(
            "singleton", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("holder_id", sa.Text(), nullable=False),
        sa.Column("renewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "lease_duration",
            sa.Interval(),
            server_default=sa.text("'30 seconds'"),
            nullable=False,
        ),
        sa.CheckConstraint("singleton", name="single_row"),
        sa.PrimaryKeyConstraint("singleton"),
        schema="first",
    )
    op.create_table(
        "model",
        sa.Column("access_group_name", sa.Text(), nullable=False),
        sa.Column("supported_endpoints", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reconcile_failures", sa.Integer(), nullable=False),
        sa.Column("reconcile_last_error", sa.Text(), nullable=True),
        sa.Column("reconcile_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_group_name"],
            ["first.access_group.name"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("name"),
        schema="first",
    )
    op.create_table(
        "pilot_job",
        sa.Column("cluster_name", sa.Text(), nullable=False),
        sa.Column("scheduler_job_id", sa.String(), nullable=True),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column("manager_url", sa.String(), nullable=True),
        sa.Column("manager_health", sa.String(), nullable=False),
        sa.Column("resources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("time_started", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idle_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("walltime_min", sa.Integer(), nullable=False),
        sa.Column("num_nodes", sa.Integer(), nullable=False),
        sa.Column("gpus_per_node", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reconcile_failures", sa.Integer(), nullable=False),
        sa.Column("reconcile_last_error", sa.Text(), nullable=True),
        sa.Column("reconcile_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.Column("scheduled_deletion", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_name"], ["first.cluster.name"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("name"),
        schema="first",
    )
    op.create_index(
        op.f("ix_first_pilot_job_cluster_name"),
        "pilot_job",
        ["cluster_name"],
        unique=False,
        schema="first",
    )
    op.create_table(
        "pilot_deployment",
        sa.Column("cluster_name", sa.Text(), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column(
            "router_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("health_check_method", sa.String(), nullable=False),
        sa.Column(
            "health_check_kwargs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("prometheus_metrics_path", sa.String(), nullable=True),
        sa.Column("prometheus_scrape_interval_sec", sa.Integer(), nullable=False),
        sa.Column(
            "scaling_strategy", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("min_replicas", sa.Integer(), nullable=False),
        sa.Column("max_replicas", sa.Integer(), nullable=False),
        sa.Column(
            "launch_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("desired_replicas", sa.Integer(), nullable=False),
        sa.Column("health", sa.String(), nullable=False),
        sa.Column("last_health_check", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_launch_failures", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reconcile_failures", sa.Integer(), nullable=False),
        sa.Column("reconcile_last_error", sa.Text(), nullable=True),
        sa.Column("reconcile_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_name"],
            ["first.cluster.name"],
        ),
        sa.ForeignKeyConstraint(
            ["model_name"],
            ["first.model.name"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("name"),
        schema="first",
    )
    op.create_index(
        op.f("ix_first_pilot_deployment_cluster_name"),
        "pilot_deployment",
        ["cluster_name"],
        unique=False,
        schema="first",
    )
    op.create_index(
        op.f("ix_first_pilot_deployment_model_name"),
        "pilot_deployment",
        ["model_name"],
        unique=False,
        schema="first",
    )
    op.create_table(
        "static_deployment",
        sa.Column("cluster_name", sa.Text(), nullable=False),
        sa.Column("model_name", sa.Text(), nullable=False),
        sa.Column("api_url", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=True),
        sa.Column("upstream_model_name", sa.String(), nullable=False),
        sa.Column(
            "router_params", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("health_check_method", sa.String(), nullable=False),
        sa.Column(
            "health_check_kwargs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("prometheus_metrics_path", sa.String(), nullable=True),
        sa.Column("prometheus_scrape_interval_sec", sa.Integer(), nullable=False),
        sa.Column("health", sa.String(), nullable=False),
        sa.Column("last_health_check", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reconcile_failures", sa.Integer(), nullable=False),
        sa.Column("reconcile_last_error", sa.Text(), nullable=True),
        sa.Column("reconcile_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_name"],
            ["first.cluster.name"],
        ),
        sa.ForeignKeyConstraint(
            ["model_name"],
            ["first.model.name"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("name"),
        schema="first",
    )
    op.create_index(
        op.f("ix_first_static_deployment_cluster_name"),
        "static_deployment",
        ["cluster_name"],
        unique=False,
        schema="first",
    )
    op.create_index(
        op.f("ix_first_static_deployment_model_name"),
        "static_deployment",
        ["model_name"],
        unique=False,
        schema="first",
    )
    op.create_table(
        "pilot_replica",
        sa.Column("pilot_deployment_name", sa.Text(), nullable=False),
        sa.Column("pilot_job_name", sa.Text(), nullable=True),
        sa.Column(
            "used_resources", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("model_url", sa.String(), nullable=True),
        sa.Column("observed_served_name", sa.String(), nullable=True),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column("status_info", sa.String(), nullable=False),
        sa.Column("last_health_check", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reconcile_failures", sa.Integer(), nullable=False),
        sa.Column("reconcile_last_error", sa.Text(), nullable=True),
        sa.Column("reconcile_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uid", sa.BigInteger(), nullable=False),
        sa.Column("scheduled_deletion", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pilot_deployment_name"],
            ["first.pilot_deployment.name"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pilot_job_name"], ["first.pilot_job.name"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("name"),
        schema="first",
    )
    op.create_index(
        op.f("ix_first_pilot_replica_pilot_deployment_name"),
        "pilot_replica",
        ["pilot_deployment_name"],
        unique=False,
        schema="first",
    )
    op.create_index(
        op.f("ix_first_pilot_replica_pilot_job_name"),
        "pilot_replica",
        ["pilot_job_name"],
        unique=False,
        schema="first",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_first_pilot_replica_pilot_job_name"),
        table_name="pilot_replica",
        schema="first",
    )
    op.drop_index(
        op.f("ix_first_pilot_replica_pilot_deployment_name"),
        table_name="pilot_replica",
        schema="first",
    )
    op.drop_table("pilot_replica", schema="first")
    op.drop_index(
        op.f("ix_first_static_deployment_model_name"),
        table_name="static_deployment",
        schema="first",
    )
    op.drop_index(
        op.f("ix_first_static_deployment_cluster_name"),
        table_name="static_deployment",
        schema="first",
    )
    op.drop_table("static_deployment", schema="first")
    op.drop_index(
        op.f("ix_first_pilot_deployment_model_name"),
        table_name="pilot_deployment",
        schema="first",
    )
    op.drop_index(
        op.f("ix_first_pilot_deployment_cluster_name"),
        table_name="pilot_deployment",
        schema="first",
    )
    op.drop_table("pilot_deployment", schema="first")
    op.drop_index(
        op.f("ix_first_pilot_job_cluster_name"), table_name="pilot_job", schema="first"
    )
    op.drop_table("pilot_job", schema="first")
    op.drop_table("model", schema="first")
    op.drop_table("controller_manager_lease", schema="first")
    op.drop_table("config_version", schema="first")
    op.drop_table("cluster", schema="first")
    op.drop_table("access_group", schema="first")
    # ### end Alembic commands ###
