# Generated by Django 5.2.15 on 2026-08-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server_async', '0013_batchlog_denormalize_access_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesslog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='access_log',
        ),
        migrations.RemoveField(
            model_name='batchmetrics',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='requestmetrics',
            name='request',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='AccessLog',
        ),
        migrations.DeleteModel(
            name='BatchMetrics',
        ),
        migrations.DeleteModel(
            name='RequestLog',
        ),
        migrations.DeleteModel(
            name='RequestMetrics',
        ),
    ]
