// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  applyResourcesControlV1ApplyPost,
  chatCompletionsFederatedV1ChatCompletionsPost,
  embeddingsFederatedV1EmbeddingsPost,
  getClusterCatalogV1ClustersNameGet,
  getConfigVersionControlV1ConfigVersionsUidGet,
  getPilotDeploymentCatalogV1DeploymentsPilotNameGet,
  getSystemHealthCatalogV1SystemHealthGet,
  healthHealthGet,
  listAccessGroupsCatalogV1AccessGroupsGet,
  listClustersCatalogV1ClustersGet,
  listConfigVersionsControlV1ConfigVersionsGet,
  listModelsCatalogV1ModelsGet,
  listPilotDeploymentsCatalogV1DeploymentsPilotGet,
  listStaticDeploymentsCatalogV1DeploymentsStaticGet,
  type Options,
  planResourcesControlV1PlanPost,
  prometheusServiceDiscoveryDiscoveryV1PrometheusGet,
  reconcileResetControlV1ReconcileResetPost,
  responsesFederatedV1ResponsesPost,
  setDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPut,
  tailReplicaLogsControlV1PilotReplicasNameLogsGet,
  whoamiWhoamiGet,
} from "../sdk.gen";
import type {
  ApplyResourcesControlV1ApplyPostData,
  ApplyResourcesControlV1ApplyPostError,
  ApplyResourcesControlV1ApplyPostResponse,
  ChatCompletionsFederatedV1ChatCompletionsPostData,
  ChatCompletionsFederatedV1ChatCompletionsPostError,
  EmbeddingsFederatedV1EmbeddingsPostData,
  EmbeddingsFederatedV1EmbeddingsPostError,
  GetClusterCatalogV1ClustersNameGetData,
  GetClusterCatalogV1ClustersNameGetError,
  GetClusterCatalogV1ClustersNameGetResponse,
  GetConfigVersionControlV1ConfigVersionsUidGetData,
  GetConfigVersionControlV1ConfigVersionsUidGetError,
  GetConfigVersionControlV1ConfigVersionsUidGetResponse,
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetData,
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetError,
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponse,
  GetSystemHealthCatalogV1SystemHealthGetData,
  GetSystemHealthCatalogV1SystemHealthGetResponse,
  HealthHealthGetData,
  HealthHealthGetResponse,
  ListAccessGroupsCatalogV1AccessGroupsGetData,
  ListAccessGroupsCatalogV1AccessGroupsGetResponse,
  ListClustersCatalogV1ClustersGetData,
  ListClustersCatalogV1ClustersGetResponse,
  ListConfigVersionsControlV1ConfigVersionsGetData,
  ListConfigVersionsControlV1ConfigVersionsGetResponse,
  ListModelsCatalogV1ModelsGetData,
  ListModelsCatalogV1ModelsGetResponse,
  ListPilotDeploymentsCatalogV1DeploymentsPilotGetData,
  ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponse,
  ListStaticDeploymentsCatalogV1DeploymentsStaticGetData,
  ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponse,
  PlanResourcesControlV1PlanPostData,
  PlanResourcesControlV1PlanPostError,
  PlanResourcesControlV1PlanPostResponse,
  PrometheusServiceDiscoveryDiscoveryV1PrometheusGetData,
  PrometheusServiceDiscoveryDiscoveryV1PrometheusGetResponse,
  ReconcileResetControlV1ReconcileResetPostData,
  ReconcileResetControlV1ReconcileResetPostError,
  ReconcileResetControlV1ReconcileResetPostResponse,
  ResponsesFederatedV1ResponsesPostData,
  ResponsesFederatedV1ResponsesPostError,
  SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutData,
  SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutError,
  SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutResponse,
  TailReplicaLogsControlV1PilotReplicasNameLogsGetData,
  TailReplicaLogsControlV1PilotReplicasNameLogsGetError,
  TailReplicaLogsControlV1PilotReplicasNameLogsGetResponse,
  WhoamiWhoamiGetData,
  WhoamiWhoamiGetResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthHealthGetQueryKey = (
  options?: Options<HealthHealthGetData>,
) => createQueryKey("healthHealthGet", options);

/**
 * Health
 *
 * Liveness probe
 */
export const healthHealthGetOptions = (
  options?: Options<HealthHealthGetData>,
) =>
  queryOptions<
    HealthHealthGetResponse,
    DefaultError,
    HealthHealthGetResponse,
    ReturnType<typeof healthHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthHealthGetQueryKey(options),
  });

export const prometheusServiceDiscoveryDiscoveryV1PrometheusGetQueryKey = (
  options?: Options<PrometheusServiceDiscoveryDiscoveryV1PrometheusGetData>,
) =>
  createQueryKey("prometheusServiceDiscoveryDiscoveryV1PrometheusGet", options);

/**
 * Prometheus Service Discovery
 *
 * Prometheus HTTP Service Discovery endpoint for live model backends.
 *
 * Advertises every live backend whose deployment exposes a
 * `prometheus_metrics_path` as a scrape target.  The metrics URL is split
 * into the `__address__`/`__scheme__`/`__metrics_path__` magic labels so a
 * single host:port can host many distinct metrics paths; `__scrape_interval__`
 * carries the deployment's scrape interval.  `instance` is pinned to the
 * unique, non-recycling backend id rather than the (shared) address.
 *
 * Returns HTTP 200 with an empty list when there are no targets.  The whole
 * target list is returned on every scrape; Prometheus keeps its cached list
 * if a refresh fails.
 */
export const prometheusServiceDiscoveryDiscoveryV1PrometheusGetOptions = (
  options?: Options<PrometheusServiceDiscoveryDiscoveryV1PrometheusGetData>,
) =>
  queryOptions<
    PrometheusServiceDiscoveryDiscoveryV1PrometheusGetResponse,
    DefaultError,
    PrometheusServiceDiscoveryDiscoveryV1PrometheusGetResponse,
    ReturnType<
      typeof prometheusServiceDiscoveryDiscoveryV1PrometheusGetQueryKey
    >
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await prometheusServiceDiscoveryDiscoveryV1PrometheusGet(
        {
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        },
      );
      return data;
    },
    queryKey:
      prometheusServiceDiscoveryDiscoveryV1PrometheusGetQueryKey(options),
  });

export const whoamiWhoamiGetQueryKey = (
  options?: Options<WhoamiWhoamiGetData>,
) => createQueryKey("whoamiWhoamiGet", options);

/**
 * Whoami
 *
 * Return the authenticated caller's identity.
 */
export const whoamiWhoamiGetOptions = (
  options?: Options<WhoamiWhoamiGetData>,
) =>
  queryOptions<
    WhoamiWhoamiGetResponse,
    DefaultError,
    WhoamiWhoamiGetResponse,
    ReturnType<typeof whoamiWhoamiGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await whoamiWhoamiGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: whoamiWhoamiGetQueryKey(options),
  });

export const listAccessGroupsCatalogV1AccessGroupsGetQueryKey = (
  options?: Options<ListAccessGroupsCatalogV1AccessGroupsGetData>,
) => createQueryKey("listAccessGroupsCatalogV1AccessGroupsGet", options);

/**
 * List Access Groups
 *
 * List AccessGroups.  Admins see all; ordinary users see only the AccessGroups
 * they qualify for.
 */
export const listAccessGroupsCatalogV1AccessGroupsGetOptions = (
  options?: Options<ListAccessGroupsCatalogV1AccessGroupsGetData>,
) =>
  queryOptions<
    ListAccessGroupsCatalogV1AccessGroupsGetResponse,
    DefaultError,
    ListAccessGroupsCatalogV1AccessGroupsGetResponse,
    ReturnType<typeof listAccessGroupsCatalogV1AccessGroupsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAccessGroupsCatalogV1AccessGroupsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAccessGroupsCatalogV1AccessGroupsGetQueryKey(options),
  });

export const listModelsCatalogV1ModelsGetQueryKey = (
  options?: Options<ListModelsCatalogV1ModelsGetData>,
) => createQueryKey("listModelsCatalogV1ModelsGet", options);

/**
 * List Models
 *
 * List Models.  Admins see all; ordinary users see only Models whose
 * AccessGroup grants them access.
 */
export const listModelsCatalogV1ModelsGetOptions = (
  options?: Options<ListModelsCatalogV1ModelsGetData>,
) =>
  queryOptions<
    ListModelsCatalogV1ModelsGetResponse,
    DefaultError,
    ListModelsCatalogV1ModelsGetResponse,
    ReturnType<typeof listModelsCatalogV1ModelsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listModelsCatalogV1ModelsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listModelsCatalogV1ModelsGetQueryKey(options),
  });

export const listPilotDeploymentsCatalogV1DeploymentsPilotGetQueryKey = (
  options?: Options<ListPilotDeploymentsCatalogV1DeploymentsPilotGetData>,
) =>
  createQueryKey("listPilotDeploymentsCatalogV1DeploymentsPilotGet", options);

/**
 * List Pilot Deployments
 *
 * List PilotDeployments.  Admins see all; ordinary users see only deployments
 * whose parent Model authorizes them.
 */
export const listPilotDeploymentsCatalogV1DeploymentsPilotGetOptions = (
  options?: Options<ListPilotDeploymentsCatalogV1DeploymentsPilotGetData>,
) =>
  queryOptions<
    ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponse,
    DefaultError,
    ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponse,
    ReturnType<typeof listPilotDeploymentsCatalogV1DeploymentsPilotGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listPilotDeploymentsCatalogV1DeploymentsPilotGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listPilotDeploymentsCatalogV1DeploymentsPilotGetQueryKey(options),
  });

export const getPilotDeploymentCatalogV1DeploymentsPilotNameGetQueryKey = (
  options: Options<GetPilotDeploymentCatalogV1DeploymentsPilotNameGetData>,
) =>
  createQueryKey("getPilotDeploymentCatalogV1DeploymentsPilotNameGet", options);

/**
 * Get Pilot Deployment
 *
 * Get a single PilotDeployment with its replicas.
 */
export const getPilotDeploymentCatalogV1DeploymentsPilotNameGetOptions = (
  options: Options<GetPilotDeploymentCatalogV1DeploymentsPilotNameGetData>,
) =>
  queryOptions<
    GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponse,
    GetPilotDeploymentCatalogV1DeploymentsPilotNameGetError,
    GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponse,
    ReturnType<
      typeof getPilotDeploymentCatalogV1DeploymentsPilotNameGetQueryKey
    >
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPilotDeploymentCatalogV1DeploymentsPilotNameGet(
        {
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        },
      );
      return data;
    },
    queryKey:
      getPilotDeploymentCatalogV1DeploymentsPilotNameGetQueryKey(options),
  });

export const listStaticDeploymentsCatalogV1DeploymentsStaticGetQueryKey = (
  options?: Options<ListStaticDeploymentsCatalogV1DeploymentsStaticGetData>,
) =>
  createQueryKey("listStaticDeploymentsCatalogV1DeploymentsStaticGet", options);

/**
 * List Static Deployments
 *
 * List StaticDeployments.  Admins see all; ordinary users see only deployments
 * whose parent Model authorizes them.
 */
export const listStaticDeploymentsCatalogV1DeploymentsStaticGetOptions = (
  options?: Options<ListStaticDeploymentsCatalogV1DeploymentsStaticGetData>,
) =>
  queryOptions<
    ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponse,
    DefaultError,
    ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponse,
    ReturnType<
      typeof listStaticDeploymentsCatalogV1DeploymentsStaticGetQueryKey
    >
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listStaticDeploymentsCatalogV1DeploymentsStaticGet(
        {
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        },
      );
      return data;
    },
    queryKey:
      listStaticDeploymentsCatalogV1DeploymentsStaticGetQueryKey(options),
  });

export const listClustersCatalogV1ClustersGetQueryKey = (
  options?: Options<ListClustersCatalogV1ClustersGetData>,
) => createQueryKey("listClustersCatalogV1ClustersGet", options);

/**
 * List Clusters
 *
 * List all configured Cluster resources.  Visible to all users.
 */
export const listClustersCatalogV1ClustersGetOptions = (
  options?: Options<ListClustersCatalogV1ClustersGetData>,
) =>
  queryOptions<
    ListClustersCatalogV1ClustersGetResponse,
    DefaultError,
    ListClustersCatalogV1ClustersGetResponse,
    ReturnType<typeof listClustersCatalogV1ClustersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listClustersCatalogV1ClustersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listClustersCatalogV1ClustersGetQueryKey(options),
  });

/**
 * Chat Completions
 */
export const chatCompletionsFederatedV1ChatCompletionsPostMutation = (
  options?: Partial<Options<ChatCompletionsFederatedV1ChatCompletionsPostData>>,
): UseMutationOptions<
  unknown,
  ChatCompletionsFederatedV1ChatCompletionsPostError,
  Options<ChatCompletionsFederatedV1ChatCompletionsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    ChatCompletionsFederatedV1ChatCompletionsPostError,
    Options<ChatCompletionsFederatedV1ChatCompletionsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await chatCompletionsFederatedV1ChatCompletionsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Responses
 */
export const responsesFederatedV1ResponsesPostMutation = (
  options?: Partial<Options<ResponsesFederatedV1ResponsesPostData>>,
): UseMutationOptions<
  unknown,
  ResponsesFederatedV1ResponsesPostError,
  Options<ResponsesFederatedV1ResponsesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    ResponsesFederatedV1ResponsesPostError,
    Options<ResponsesFederatedV1ResponsesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await responsesFederatedV1ResponsesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Embeddings
 */
export const embeddingsFederatedV1EmbeddingsPostMutation = (
  options?: Partial<Options<EmbeddingsFederatedV1EmbeddingsPostData>>,
): UseMutationOptions<
  unknown,
  EmbeddingsFederatedV1EmbeddingsPostError,
  Options<EmbeddingsFederatedV1EmbeddingsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    EmbeddingsFederatedV1EmbeddingsPostError,
    Options<EmbeddingsFederatedV1EmbeddingsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await embeddingsFederatedV1EmbeddingsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSystemHealthCatalogV1SystemHealthGetQueryKey = (
  options?: Options<GetSystemHealthCatalogV1SystemHealthGetData>,
) => createQueryKey("getSystemHealthCatalogV1SystemHealthGet", options);

/**
 * Get System Health
 *
 * One-glance operational snapshot: the health/state and any reconcile error
 * of every operational resource, grouped by type.  Admin-only.
 */
export const getSystemHealthCatalogV1SystemHealthGetOptions = (
  options?: Options<GetSystemHealthCatalogV1SystemHealthGetData>,
) =>
  queryOptions<
    GetSystemHealthCatalogV1SystemHealthGetResponse,
    DefaultError,
    GetSystemHealthCatalogV1SystemHealthGetResponse,
    ReturnType<typeof getSystemHealthCatalogV1SystemHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSystemHealthCatalogV1SystemHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSystemHealthCatalogV1SystemHealthGetQueryKey(options),
  });

export const getClusterCatalogV1ClustersNameGetQueryKey = (
  options: Options<GetClusterCatalogV1ClustersNameGetData>,
) => createQueryKey("getClusterCatalogV1ClustersNameGet", options);

/**
 * Get Cluster
 *
 * Get a Cluster with its pilot jobs.  Admin-only: pilot job details are
 * sensitive operational state.
 */
export const getClusterCatalogV1ClustersNameGetOptions = (
  options: Options<GetClusterCatalogV1ClustersNameGetData>,
) =>
  queryOptions<
    GetClusterCatalogV1ClustersNameGetResponse,
    GetClusterCatalogV1ClustersNameGetError,
    GetClusterCatalogV1ClustersNameGetResponse,
    ReturnType<typeof getClusterCatalogV1ClustersNameGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getClusterCatalogV1ClustersNameGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getClusterCatalogV1ClustersNameGetQueryKey(options),
  });

/**
 * Plan Resources
 *
 * Create a plan for applying a set of resources without actually applying them.
 *
 * Returns a ResourceChangePlan describing what would be added, updated,
 * deleted, or left unchanged.  This is the "Plan" phase of a Plan/Apply
 * workflow.  The caller reviews the plan and then submits it back to the Apply
 * endpoint to commit changes.
 */
export const planResourcesControlV1PlanPostMutation = (
  options?: Partial<Options<PlanResourcesControlV1PlanPostData>>,
): UseMutationOptions<
  PlanResourcesControlV1PlanPostResponse,
  PlanResourcesControlV1PlanPostError,
  Options<PlanResourcesControlV1PlanPostData>
> => {
  const mutationOptions: UseMutationOptions<
    PlanResourcesControlV1PlanPostResponse,
    PlanResourcesControlV1PlanPostError,
    Options<PlanResourcesControlV1PlanPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await planResourcesControlV1PlanPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Apply Resources
 *
 * Apply a previously-approved plan.
 *
 * Takes the same resources and an approved ResourceChangePlan (one that
 * was returned by the /plan endpoint and reviewed by the caller).
 * Performs a two-phase commit: replans the current state and only
 * proceeds if it matches the approved plan, ensuring no concurrent
 * modifications have occurred.
 */
export const applyResourcesControlV1ApplyPostMutation = (
  options?: Partial<Options<ApplyResourcesControlV1ApplyPostData>>,
): UseMutationOptions<
  ApplyResourcesControlV1ApplyPostResponse,
  ApplyResourcesControlV1ApplyPostError,
  Options<ApplyResourcesControlV1ApplyPostData>
> => {
  const mutationOptions: UseMutationOptions<
    ApplyResourcesControlV1ApplyPostResponse,
    ApplyResourcesControlV1ApplyPostError,
    Options<ApplyResourcesControlV1ApplyPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await applyResourcesControlV1ApplyPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listConfigVersionsControlV1ConfigVersionsGetQueryKey = (
  options?: Options<ListConfigVersionsControlV1ConfigVersionsGetData>,
) => createQueryKey("listConfigVersionsControlV1ConfigVersionsGet", options);

/**
 * List Config Versions
 *
 * List all recorded ConfigVersions
 */
export const listConfigVersionsControlV1ConfigVersionsGetOptions = (
  options?: Options<ListConfigVersionsControlV1ConfigVersionsGetData>,
) =>
  queryOptions<
    ListConfigVersionsControlV1ConfigVersionsGetResponse,
    DefaultError,
    ListConfigVersionsControlV1ConfigVersionsGetResponse,
    ReturnType<typeof listConfigVersionsControlV1ConfigVersionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listConfigVersionsControlV1ConfigVersionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listConfigVersionsControlV1ConfigVersionsGetQueryKey(options),
  });

export const getConfigVersionControlV1ConfigVersionsUidGetQueryKey = (
  options: Options<GetConfigVersionControlV1ConfigVersionsUidGetData>,
) => createQueryKey("getConfigVersionControlV1ConfigVersionsUidGet", options);

/**
 * Get Config Version
 *
 * Get a single ConfigVersion by uid, including the full `changes` record.
 */
export const getConfigVersionControlV1ConfigVersionsUidGetOptions = (
  options: Options<GetConfigVersionControlV1ConfigVersionsUidGetData>,
) =>
  queryOptions<
    GetConfigVersionControlV1ConfigVersionsUidGetResponse,
    GetConfigVersionControlV1ConfigVersionsUidGetError,
    GetConfigVersionControlV1ConfigVersionsUidGetResponse,
    ReturnType<typeof getConfigVersionControlV1ConfigVersionsUidGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getConfigVersionControlV1ConfigVersionsUidGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getConfigVersionControlV1ConfigVersionsUidGetQueryKey(options),
  });

/**
 * Set Desired Pilot Replicas
 *
 * Manually set desired scale of a PilotDeployment
 */
export const setDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutMutation =
  (
    options?: Partial<
      Options<SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutData>
    >,
  ): UseMutationOptions<
    SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutResponse,
    SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutError,
    Options<SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutData>
  > => {
    const mutationOptions: UseMutationOptions<
      SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutResponse,
      SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutError,
      Options<SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await setDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPut(
            {
              ...options,
              ...fnOptions,
              throwOnError: true,
            },
          );
        return data;
      },
    };
    return mutationOptions;
  };

/**
 * Reconcile Reset
 *
 * Reset reconcile backoff state for a resource and its children.
 */
export const reconcileResetControlV1ReconcileResetPostMutation = (
  options?: Partial<Options<ReconcileResetControlV1ReconcileResetPostData>>,
): UseMutationOptions<
  ReconcileResetControlV1ReconcileResetPostResponse,
  ReconcileResetControlV1ReconcileResetPostError,
  Options<ReconcileResetControlV1ReconcileResetPostData>
> => {
  const mutationOptions: UseMutationOptions<
    ReconcileResetControlV1ReconcileResetPostResponse,
    ReconcileResetControlV1ReconcileResetPostError,
    Options<ReconcileResetControlV1ReconcileResetPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await reconcileResetControlV1ReconcileResetPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const tailReplicaLogsControlV1PilotReplicasNameLogsGetQueryKey = (
  options: Options<TailReplicaLogsControlV1PilotReplicasNameLogsGetData>,
) =>
  createQueryKey("tailReplicaLogsControlV1PilotReplicasNameLogsGet", options);

/**
 * Tail Replica Logs
 *
 * Read tail of logs generated by replica
 */
export const tailReplicaLogsControlV1PilotReplicasNameLogsGetOptions = (
  options: Options<TailReplicaLogsControlV1PilotReplicasNameLogsGetData>,
) =>
  queryOptions<
    TailReplicaLogsControlV1PilotReplicasNameLogsGetResponse,
    TailReplicaLogsControlV1PilotReplicasNameLogsGetError,
    TailReplicaLogsControlV1PilotReplicasNameLogsGetResponse,
    ReturnType<typeof tailReplicaLogsControlV1PilotReplicasNameLogsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await tailReplicaLogsControlV1PilotReplicasNameLogsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: tailReplicaLogsControlV1PilotReplicasNameLogsGetQueryKey(options),
  });
