// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  chatCompletionsFederatedV1ChatCompletionsPost,
  chatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPost,
  clusterJobsResourceServerClusterJobsGet,
  clusterModelsResourceServerClusterModelsGet,
  deploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPost,
  deploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPost,
  deploymentMessagesDeploymentsDeploymentSlugV1MessagesPost,
  deploymentResponsesDeploymentsDeploymentSlugV1ResponsesPost,
  deploymentTasksDeploymentsDeploymentSlugV1TasksPost,
  embeddingsFederatedV1EmbeddingsPost,
  embeddingsResourceServerClusterFrameworkV1EmbeddingsPost,
  ensureStagingAreaResourceServerStagingPut,
  getClusterCatalogV1ClustersNameGet,
  getPilotDeploymentCatalogV1DeploymentsPilotNameGet,
  getRouterConfigCatalogV1RouterConfigGet,
  getSystemHealthCatalogV1SystemHealthGet,
  healthHealthGet,
  healthResourceServerHealthGet,
  listAccessGroupsCatalogV1AccessGroupsGet,
  listClustersCatalogV1ClustersGet,
  listDeploymentModelsDeploymentsDeploymentSlugV1ModelsGet,
  listEndpointsResourceServerListEndpointsGet,
  listLaunchTemplatesCatalogV1LaunchTemplatesGet,
  listModelsCatalogV1ModelsGet,
  listModelsFederatedV1ModelsGet,
  listPilotDeploymentsCatalogV1DeploymentsPilotGet,
  listStaticDeploymentsCatalogV1DeploymentsStaticGet,
  messagesFederatedV1MessagesPost,
  messagesResourceServerClusterFrameworkV1MessagesPost,
  type Options,
  responsesFederatedV1ResponsesPost,
  responsesResourceServerClusterFrameworkV1ResponsesPost,
  tailReplicaLogsCatalogV1PilotReplicasSlugLogsGet,
  tasksFederatedV1TasksPost,
  whoamiResourceServerWhoamiGet,
  whoamiWhoamiGet,
} from "../sdk.gen";
import type {
  ChatCompletionsFederatedV1ChatCompletionsPostData,
  ChatCompletionsFederatedV1ChatCompletionsPostError,
  ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostData,
  ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostError,
  ClusterJobsResourceServerClusterJobsGetData,
  ClusterJobsResourceServerClusterJobsGetError,
  ClusterJobsResourceServerClusterJobsGetResponse,
  ClusterModelsResourceServerClusterModelsGetData,
  ClusterModelsResourceServerClusterModelsGetError,
  ClusterModelsResourceServerClusterModelsGetResponse,
  DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostData,
  DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostError,
  DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostData,
  DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostError,
  DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostData,
  DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostError,
  DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostData,
  DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostError,
  DeploymentTasksDeploymentsDeploymentSlugV1TasksPostData,
  DeploymentTasksDeploymentsDeploymentSlugV1TasksPostError,
  EmbeddingsFederatedV1EmbeddingsPostData,
  EmbeddingsFederatedV1EmbeddingsPostError,
  EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostData,
  EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostError,
  EnsureStagingAreaResourceServerStagingPutData,
  EnsureStagingAreaResourceServerStagingPutResponse,
  GetClusterCatalogV1ClustersNameGetData,
  GetClusterCatalogV1ClustersNameGetError,
  GetClusterCatalogV1ClustersNameGetResponse,
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetData,
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetError,
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponse,
  GetRouterConfigCatalogV1RouterConfigGetData,
  GetRouterConfigCatalogV1RouterConfigGetResponse,
  GetSystemHealthCatalogV1SystemHealthGetData,
  GetSystemHealthCatalogV1SystemHealthGetResponse,
  HealthHealthGetData,
  HealthHealthGetResponse,
  HealthResourceServerHealthGetData,
  HealthResourceServerHealthGetResponse,
  ListAccessGroupsCatalogV1AccessGroupsGetData,
  ListAccessGroupsCatalogV1AccessGroupsGetResponse,
  ListClustersCatalogV1ClustersGetData,
  ListClustersCatalogV1ClustersGetResponse,
  ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetData,
  ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetError,
  ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetResponse,
  ListEndpointsResourceServerListEndpointsGetData,
  ListEndpointsResourceServerListEndpointsGetResponse,
  ListLaunchTemplatesCatalogV1LaunchTemplatesGetData,
  ListLaunchTemplatesCatalogV1LaunchTemplatesGetResponse,
  ListModelsCatalogV1ModelsGetData,
  ListModelsCatalogV1ModelsGetResponse,
  ListModelsFederatedV1ModelsGetData,
  ListModelsFederatedV1ModelsGetResponse,
  ListPilotDeploymentsCatalogV1DeploymentsPilotGetData,
  ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponse,
  ListStaticDeploymentsCatalogV1DeploymentsStaticGetData,
  ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponse,
  MessagesFederatedV1MessagesPostData,
  MessagesFederatedV1MessagesPostError,
  MessagesResourceServerClusterFrameworkV1MessagesPostData,
  MessagesResourceServerClusterFrameworkV1MessagesPostError,
  ResponsesFederatedV1ResponsesPostData,
  ResponsesFederatedV1ResponsesPostError,
  ResponsesResourceServerClusterFrameworkV1ResponsesPostData,
  ResponsesResourceServerClusterFrameworkV1ResponsesPostError,
  TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetData,
  TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetError,
  TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetResponse,
  TasksFederatedV1TasksPostData,
  TasksFederatedV1TasksPostError,
  WhoamiResourceServerWhoamiGetData,
  WhoamiResourceServerWhoamiGetResponse,
  WhoamiWhoamiGetData,
  WhoamiWhoamiGetResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthHealthGetQueryKey = (
  options?: Options<HealthHealthGetData>,
) => createQueryKey("healthHealthGet", options);

/**
 * Health
 *
 * Liveness probe
 */
export const healthHealthGetOptions = (
  options?: Options<HealthHealthGetData>,
) =>
  queryOptions<
    HealthHealthGetResponse,
    DefaultError,
    HealthHealthGetResponse,
    ReturnType<typeof healthHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthHealthGetQueryKey(options),
  });

export const healthResourceServerHealthGetQueryKey = (
  options?: Options<HealthResourceServerHealthGetData>,
) => createQueryKey("healthResourceServerHealthGet", options);

/**
 * Health
 */
export const healthResourceServerHealthGetOptions = (
  options?: Options<HealthResourceServerHealthGetData>,
) =>
  queryOptions<
    HealthResourceServerHealthGetResponse,
    DefaultError,
    HealthResourceServerHealthGetResponse,
    ReturnType<typeof healthResourceServerHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthResourceServerHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthResourceServerHealthGetQueryKey(options),
  });

export const whoamiWhoamiGetQueryKey = (
  options?: Options<WhoamiWhoamiGetData>,
) => createQueryKey("whoamiWhoamiGet", options);

/**
 * Whoami
 *
 * Return the authenticated caller's identity.
 */
export const whoamiWhoamiGetOptions = (
  options?: Options<WhoamiWhoamiGetData>,
) =>
  queryOptions<
    WhoamiWhoamiGetResponse,
    DefaultError,
    WhoamiWhoamiGetResponse,
    ReturnType<typeof whoamiWhoamiGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await whoamiWhoamiGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: whoamiWhoamiGetQueryKey(options),
  });

export const listAccessGroupsCatalogV1AccessGroupsGetQueryKey = (
  options?: Options<ListAccessGroupsCatalogV1AccessGroupsGetData>,
) => createQueryKey("listAccessGroupsCatalogV1AccessGroupsGet", options);

/**
 * List Access Groups
 *
 * List AccessGroups.  Admins see all; ordinary users see only the AccessGroups
 * they qualify for.
 */
export const listAccessGroupsCatalogV1AccessGroupsGetOptions = (
  options?: Options<ListAccessGroupsCatalogV1AccessGroupsGetData>,
) =>
  queryOptions<
    ListAccessGroupsCatalogV1AccessGroupsGetResponse,
    DefaultError,
    ListAccessGroupsCatalogV1AccessGroupsGetResponse,
    ReturnType<typeof listAccessGroupsCatalogV1AccessGroupsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAccessGroupsCatalogV1AccessGroupsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAccessGroupsCatalogV1AccessGroupsGetQueryKey(options),
  });

export const listModelsCatalogV1ModelsGetQueryKey = (
  options?: Options<ListModelsCatalogV1ModelsGetData>,
) => createQueryKey("listModelsCatalogV1ModelsGet", options);

/**
 * List Models
 *
 * List Models.  Admins see all; ordinary users see only Models whose
 * AccessGroup grants them access.
 */
export const listModelsCatalogV1ModelsGetOptions = (
  options?: Options<ListModelsCatalogV1ModelsGetData>,
) =>
  queryOptions<
    ListModelsCatalogV1ModelsGetResponse,
    DefaultError,
    ListModelsCatalogV1ModelsGetResponse,
    ReturnType<typeof listModelsCatalogV1ModelsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listModelsCatalogV1ModelsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listModelsCatalogV1ModelsGetQueryKey(options),
  });

export const listPilotDeploymentsCatalogV1DeploymentsPilotGetQueryKey = (
  options?: Options<ListPilotDeploymentsCatalogV1DeploymentsPilotGetData>,
) =>
  createQueryKey("listPilotDeploymentsCatalogV1DeploymentsPilotGet", options);

/**
 * List Pilot Deployments
 *
 * List PilotDeployments.  Admins see all; ordinary users see only deployments
 * whose parent Model authorizes them.
 */
export const listPilotDeploymentsCatalogV1DeploymentsPilotGetOptions = (
  options?: Options<ListPilotDeploymentsCatalogV1DeploymentsPilotGetData>,
) =>
  queryOptions<
    ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponse,
    DefaultError,
    ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponse,
    ReturnType<typeof listPilotDeploymentsCatalogV1DeploymentsPilotGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listPilotDeploymentsCatalogV1DeploymentsPilotGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listPilotDeploymentsCatalogV1DeploymentsPilotGetQueryKey(options),
  });

export const getPilotDeploymentCatalogV1DeploymentsPilotNameGetQueryKey = (
  options: Options<GetPilotDeploymentCatalogV1DeploymentsPilotNameGetData>,
) =>
  createQueryKey("getPilotDeploymentCatalogV1DeploymentsPilotNameGet", options);

/**
 * Get Pilot Deployment
 *
 * Get a single PilotDeployment with its replicas.
 */
export const getPilotDeploymentCatalogV1DeploymentsPilotNameGetOptions = (
  options: Options<GetPilotDeploymentCatalogV1DeploymentsPilotNameGetData>,
) =>
  queryOptions<
    GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponse,
    GetPilotDeploymentCatalogV1DeploymentsPilotNameGetError,
    GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponse,
    ReturnType<
      typeof getPilotDeploymentCatalogV1DeploymentsPilotNameGetQueryKey
    >
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPilotDeploymentCatalogV1DeploymentsPilotNameGet(
        {
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        },
      );
      return data;
    },
    queryKey:
      getPilotDeploymentCatalogV1DeploymentsPilotNameGetQueryKey(options),
  });

export const listStaticDeploymentsCatalogV1DeploymentsStaticGetQueryKey = (
  options?: Options<ListStaticDeploymentsCatalogV1DeploymentsStaticGetData>,
) =>
  createQueryKey("listStaticDeploymentsCatalogV1DeploymentsStaticGet", options);

/**
 * List Static Deployments
 *
 * List StaticDeployments.  Admins see all; ordinary users see only deployments
 * whose parent Model authorizes them.
 */
export const listStaticDeploymentsCatalogV1DeploymentsStaticGetOptions = (
  options?: Options<ListStaticDeploymentsCatalogV1DeploymentsStaticGetData>,
) =>
  queryOptions<
    ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponse,
    DefaultError,
    ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponse,
    ReturnType<
      typeof listStaticDeploymentsCatalogV1DeploymentsStaticGetQueryKey
    >
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listStaticDeploymentsCatalogV1DeploymentsStaticGet(
        {
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        },
      );
      return data;
    },
    queryKey:
      listStaticDeploymentsCatalogV1DeploymentsStaticGetQueryKey(options),
  });

export const listClustersCatalogV1ClustersGetQueryKey = (
  options?: Options<ListClustersCatalogV1ClustersGetData>,
) => createQueryKey("listClustersCatalogV1ClustersGet", options);

/**
 * List Clusters
 *
 * List all configured Cluster resources.  Visible to all users.
 */
export const listClustersCatalogV1ClustersGetOptions = (
  options?: Options<ListClustersCatalogV1ClustersGetData>,
) =>
  queryOptions<
    ListClustersCatalogV1ClustersGetResponse,
    DefaultError,
    ListClustersCatalogV1ClustersGetResponse,
    ReturnType<typeof listClustersCatalogV1ClustersGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listClustersCatalogV1ClustersGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listClustersCatalogV1ClustersGetQueryKey(options),
  });

/**
 * Chat Completions
 */
export const chatCompletionsFederatedV1ChatCompletionsPostMutation = (
  options?: Partial<Options<ChatCompletionsFederatedV1ChatCompletionsPostData>>,
): UseMutationOptions<
  unknown,
  ChatCompletionsFederatedV1ChatCompletionsPostError,
  Options<ChatCompletionsFederatedV1ChatCompletionsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    ChatCompletionsFederatedV1ChatCompletionsPostError,
    Options<ChatCompletionsFederatedV1ChatCompletionsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await chatCompletionsFederatedV1ChatCompletionsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Responses
 */
export const responsesFederatedV1ResponsesPostMutation = (
  options?: Partial<Options<ResponsesFederatedV1ResponsesPostData>>,
): UseMutationOptions<
  unknown,
  ResponsesFederatedV1ResponsesPostError,
  Options<ResponsesFederatedV1ResponsesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    ResponsesFederatedV1ResponsesPostError,
    Options<ResponsesFederatedV1ResponsesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await responsesFederatedV1ResponsesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Messages
 */
export const messagesFederatedV1MessagesPostMutation = (
  options?: Partial<Options<MessagesFederatedV1MessagesPostData>>,
): UseMutationOptions<
  unknown,
  MessagesFederatedV1MessagesPostError,
  Options<MessagesFederatedV1MessagesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    MessagesFederatedV1MessagesPostError,
    Options<MessagesFederatedV1MessagesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await messagesFederatedV1MessagesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Embeddings
 */
export const embeddingsFederatedV1EmbeddingsPostMutation = (
  options?: Partial<Options<EmbeddingsFederatedV1EmbeddingsPostData>>,
): UseMutationOptions<
  unknown,
  EmbeddingsFederatedV1EmbeddingsPostError,
  Options<EmbeddingsFederatedV1EmbeddingsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    EmbeddingsFederatedV1EmbeddingsPostError,
    Options<EmbeddingsFederatedV1EmbeddingsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await embeddingsFederatedV1EmbeddingsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Tasks
 */
export const tasksFederatedV1TasksPostMutation = (
  options?: Partial<Options<TasksFederatedV1TasksPostData>>,
): UseMutationOptions<
  unknown,
  TasksFederatedV1TasksPostError,
  Options<TasksFederatedV1TasksPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    TasksFederatedV1TasksPostError,
    Options<TasksFederatedV1TasksPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await tasksFederatedV1TasksPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listModelsFederatedV1ModelsGetQueryKey = (
  options?: Options<ListModelsFederatedV1ModelsGetData>,
) => createQueryKey("listModelsFederatedV1ModelsGet", options);

/**
 * List Models
 */
export const listModelsFederatedV1ModelsGetOptions = (
  options?: Options<ListModelsFederatedV1ModelsGetData>,
) =>
  queryOptions<
    ListModelsFederatedV1ModelsGetResponse,
    DefaultError,
    ListModelsFederatedV1ModelsGetResponse,
    ReturnType<typeof listModelsFederatedV1ModelsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listModelsFederatedV1ModelsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listModelsFederatedV1ModelsGetQueryKey(options),
  });

/**
 * Deployment Chat Completions
 */
export const deploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostMutation =
  (
    options?: Partial<
      Options<DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostData>
    >,
  ): UseMutationOptions<
    unknown,
    DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostError,
    Options<DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      unknown,
      DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostError,
      Options<DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await deploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPost(
            {
              ...options,
              ...fnOptions,
              throwOnError: true,
            },
          );
        return data;
      },
    };
    return mutationOptions;
  };

/**
 * Deployment Responses
 */
export const deploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostMutation =
  (
    options?: Partial<
      Options<DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostData>
    >,
  ): UseMutationOptions<
    unknown,
    DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostError,
    Options<DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      unknown,
      DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostError,
      Options<DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await deploymentResponsesDeploymentsDeploymentSlugV1ResponsesPost({
            ...options,
            ...fnOptions,
            throwOnError: true,
          });
        return data;
      },
    };
    return mutationOptions;
  };

/**
 * Deployment Messages
 */
export const deploymentMessagesDeploymentsDeploymentSlugV1MessagesPostMutation =
  (
    options?: Partial<
      Options<DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostData>
    >,
  ): UseMutationOptions<
    unknown,
    DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostError,
    Options<DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      unknown,
      DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostError,
      Options<DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await deploymentMessagesDeploymentsDeploymentSlugV1MessagesPost({
            ...options,
            ...fnOptions,
            throwOnError: true,
          });
        return data;
      },
    };
    return mutationOptions;
  };

/**
 * Deployment Embeddings
 */
export const deploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostMutation =
  (
    options?: Partial<
      Options<DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostData>
    >,
  ): UseMutationOptions<
    unknown,
    DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostError,
    Options<DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      unknown,
      DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostError,
      Options<DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await deploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPost({
            ...options,
            ...fnOptions,
            throwOnError: true,
          });
        return data;
      },
    };
    return mutationOptions;
  };

/**
 * Deployment Tasks
 */
export const deploymentTasksDeploymentsDeploymentSlugV1TasksPostMutation = (
  options?: Partial<
    Options<DeploymentTasksDeploymentsDeploymentSlugV1TasksPostData>
  >,
): UseMutationOptions<
  unknown,
  DeploymentTasksDeploymentsDeploymentSlugV1TasksPostError,
  Options<DeploymentTasksDeploymentsDeploymentSlugV1TasksPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeploymentTasksDeploymentsDeploymentSlugV1TasksPostError,
    Options<DeploymentTasksDeploymentsDeploymentSlugV1TasksPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await deploymentTasksDeploymentsDeploymentSlugV1TasksPost({
          ...options,
          ...fnOptions,
          throwOnError: true,
        });
      return data;
    },
  };
  return mutationOptions;
};

export const listDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetQueryKey =
  (
    options: Options<ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetData>,
  ) =>
    createQueryKey(
      "listDeploymentModelsDeploymentsDeploymentSlugV1ModelsGet",
      options,
    );

/**
 * List Deployment Models
 *
 * List the model served by this deployment (visible to the caller).
 */
export const listDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetOptions = (
  options: Options<ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetData>,
) =>
  queryOptions<
    ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetResponse,
    ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetError,
    ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetResponse,
    ReturnType<
      typeof listDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetQueryKey
    >
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } =
        await listDeploymentModelsDeploymentsDeploymentSlugV1ModelsGet({
          ...options,
          ...queryKey[0],
          signal,
          throwOnError: true,
        });
      return data;
    },
    queryKey:
      listDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetQueryKey(options),
  });

export const whoamiResourceServerWhoamiGetQueryKey = (
  options?: Options<WhoamiResourceServerWhoamiGetData>,
) => createQueryKey("whoamiResourceServerWhoamiGet", options);

/**
 * Whoami
 */
export const whoamiResourceServerWhoamiGetOptions = (
  options?: Options<WhoamiResourceServerWhoamiGetData>,
) =>
  queryOptions<
    WhoamiResourceServerWhoamiGetResponse,
    DefaultError,
    WhoamiResourceServerWhoamiGetResponse,
    ReturnType<typeof whoamiResourceServerWhoamiGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await whoamiResourceServerWhoamiGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: whoamiResourceServerWhoamiGetQueryKey(options),
  });

export const listEndpointsResourceServerListEndpointsGetQueryKey = (
  options?: Options<ListEndpointsResourceServerListEndpointsGetData>,
) => createQueryKey("listEndpointsResourceServerListEndpointsGet", options);

/**
 * List Endpoints
 *
 * List available frameworks and models, grouped by the cluster each model is
 * deployed on.  Models with no deployment are invisible here.
 */
export const listEndpointsResourceServerListEndpointsGetOptions = (
  options?: Options<ListEndpointsResourceServerListEndpointsGetData>,
) =>
  queryOptions<
    ListEndpointsResourceServerListEndpointsGetResponse,
    DefaultError,
    ListEndpointsResourceServerListEndpointsGetResponse,
    ReturnType<typeof listEndpointsResourceServerListEndpointsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listEndpointsResourceServerListEndpointsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listEndpointsResourceServerListEndpointsGetQueryKey(options),
  });

export const clusterJobsResourceServerClusterJobsGetQueryKey = (
  options: Options<ClusterJobsResourceServerClusterJobsGetData>,
) => createQueryKey("clusterJobsResourceServerClusterJobsGet", options);

/**
 * Cluster Jobs
 *
 * Status of all (visible) models on a cluster, mapped into V1's grouped-by-state
 * shape.  Deployment states are mapped to running/queued/stopped/others as best
 * they fit; this is a shim, not a faithful translation.
 */
export const clusterJobsResourceServerClusterJobsGetOptions = (
  options: Options<ClusterJobsResourceServerClusterJobsGetData>,
) =>
  queryOptions<
    ClusterJobsResourceServerClusterJobsGetResponse,
    ClusterJobsResourceServerClusterJobsGetError,
    ClusterJobsResourceServerClusterJobsGetResponse,
    ReturnType<typeof clusterJobsResourceServerClusterJobsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await clusterJobsResourceServerClusterJobsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: clusterJobsResourceServerClusterJobsGetQueryKey(options),
  });

export const clusterModelsResourceServerClusterModelsGetQueryKey = (
  options: Options<ClusterModelsResourceServerClusterModelsGetData>,
) => createQueryKey("clusterModelsResourceServerClusterModelsGet", options);

/**
 * Cluster Models
 */
export const clusterModelsResourceServerClusterModelsGetOptions = (
  options: Options<ClusterModelsResourceServerClusterModelsGetData>,
) =>
  queryOptions<
    ClusterModelsResourceServerClusterModelsGetResponse,
    ClusterModelsResourceServerClusterModelsGetError,
    ClusterModelsResourceServerClusterModelsGetResponse,
    ReturnType<typeof clusterModelsResourceServerClusterModelsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await clusterModelsResourceServerClusterModelsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: clusterModelsResourceServerClusterModelsGetQueryKey(options),
  });

/**
 * Ensure Staging Area
 *
 * Idempotently create a Globus staging area for the caller.
 */
export const ensureStagingAreaResourceServerStagingPutMutation = (
  options?: Partial<Options<EnsureStagingAreaResourceServerStagingPutData>>,
): UseMutationOptions<
  EnsureStagingAreaResourceServerStagingPutResponse,
  DefaultError,
  Options<EnsureStagingAreaResourceServerStagingPutData>
> => {
  const mutationOptions: UseMutationOptions<
    EnsureStagingAreaResourceServerStagingPutResponse,
    DefaultError,
    Options<EnsureStagingAreaResourceServerStagingPutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await ensureStagingAreaResourceServerStagingPut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Chat Completions
 */
export const chatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostMutation =
  (
    options?: Partial<
      Options<ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostData>
    >,
  ): UseMutationOptions<
    unknown,
    ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostError,
    Options<ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      unknown,
      ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostError,
      Options<ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await chatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPost(
            {
              ...options,
              ...fnOptions,
              throwOnError: true,
            },
          );
        return data;
      },
    };
    return mutationOptions;
  };

/**
 * Responses
 */
export const responsesResourceServerClusterFrameworkV1ResponsesPostMutation = (
  options?: Partial<
    Options<ResponsesResourceServerClusterFrameworkV1ResponsesPostData>
  >,
): UseMutationOptions<
  unknown,
  ResponsesResourceServerClusterFrameworkV1ResponsesPostError,
  Options<ResponsesResourceServerClusterFrameworkV1ResponsesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    ResponsesResourceServerClusterFrameworkV1ResponsesPostError,
    Options<ResponsesResourceServerClusterFrameworkV1ResponsesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await responsesResourceServerClusterFrameworkV1ResponsesPost({
          ...options,
          ...fnOptions,
          throwOnError: true,
        });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Messages
 */
export const messagesResourceServerClusterFrameworkV1MessagesPostMutation = (
  options?: Partial<
    Options<MessagesResourceServerClusterFrameworkV1MessagesPostData>
  >,
): UseMutationOptions<
  unknown,
  MessagesResourceServerClusterFrameworkV1MessagesPostError,
  Options<MessagesResourceServerClusterFrameworkV1MessagesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    MessagesResourceServerClusterFrameworkV1MessagesPostError,
    Options<MessagesResourceServerClusterFrameworkV1MessagesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await messagesResourceServerClusterFrameworkV1MessagesPost({
          ...options,
          ...fnOptions,
          throwOnError: true,
        });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Embeddings
 */
export const embeddingsResourceServerClusterFrameworkV1EmbeddingsPostMutation =
  (
    options?: Partial<
      Options<EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostData>
    >,
  ): UseMutationOptions<
    unknown,
    EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostError,
    Options<EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostData>
  > => {
    const mutationOptions: UseMutationOptions<
      unknown,
      EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostError,
      Options<EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await embeddingsResourceServerClusterFrameworkV1EmbeddingsPost({
            ...options,
            ...fnOptions,
            throwOnError: true,
          });
        return data;
      },
    };
    return mutationOptions;
  };

export const listLaunchTemplatesCatalogV1LaunchTemplatesGetQueryKey = (
  options?: Options<ListLaunchTemplatesCatalogV1LaunchTemplatesGetData>,
) => createQueryKey("listLaunchTemplatesCatalogV1LaunchTemplatesGet", options);

/**
 * List Launch Templates
 */
export const listLaunchTemplatesCatalogV1LaunchTemplatesGetOptions = (
  options?: Options<ListLaunchTemplatesCatalogV1LaunchTemplatesGetData>,
) =>
  queryOptions<
    ListLaunchTemplatesCatalogV1LaunchTemplatesGetResponse,
    DefaultError,
    ListLaunchTemplatesCatalogV1LaunchTemplatesGetResponse,
    ReturnType<typeof listLaunchTemplatesCatalogV1LaunchTemplatesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listLaunchTemplatesCatalogV1LaunchTemplatesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listLaunchTemplatesCatalogV1LaunchTemplatesGetQueryKey(options),
  });

export const getClusterCatalogV1ClustersNameGetQueryKey = (
  options: Options<GetClusterCatalogV1ClustersNameGetData>,
) => createQueryKey("getClusterCatalogV1ClustersNameGet", options);

/**
 * Get Cluster
 *
 * Get a Cluster with its pilot jobs. Admin-only.
 */
export const getClusterCatalogV1ClustersNameGetOptions = (
  options: Options<GetClusterCatalogV1ClustersNameGetData>,
) =>
  queryOptions<
    GetClusterCatalogV1ClustersNameGetResponse,
    GetClusterCatalogV1ClustersNameGetError,
    GetClusterCatalogV1ClustersNameGetResponse,
    ReturnType<typeof getClusterCatalogV1ClustersNameGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getClusterCatalogV1ClustersNameGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getClusterCatalogV1ClustersNameGetQueryKey(options),
  });

export const getSystemHealthCatalogV1SystemHealthGetQueryKey = (
  options?: Options<GetSystemHealthCatalogV1SystemHealthGetData>,
) => createQueryKey("getSystemHealthCatalogV1SystemHealthGet", options);

/**
 * Get System Health
 *
 * One-glance operational snapshot: the health/state and any reconcile error
 * of every operational resource, grouped by type.  Admin-only.
 */
export const getSystemHealthCatalogV1SystemHealthGetOptions = (
  options?: Options<GetSystemHealthCatalogV1SystemHealthGetData>,
) =>
  queryOptions<
    GetSystemHealthCatalogV1SystemHealthGetResponse,
    DefaultError,
    GetSystemHealthCatalogV1SystemHealthGetResponse,
    ReturnType<typeof getSystemHealthCatalogV1SystemHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSystemHealthCatalogV1SystemHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSystemHealthCatalogV1SystemHealthGetQueryKey(options),
  });

export const getRouterConfigCatalogV1RouterConfigGetQueryKey = (
  options?: Options<GetRouterConfigCatalogV1RouterConfigGetData>,
) => createQueryKey("getRouterConfigCatalogV1RouterConfigGet", options);

/**
 * Get Router Config
 */
export const getRouterConfigCatalogV1RouterConfigGetOptions = (
  options?: Options<GetRouterConfigCatalogV1RouterConfigGetData>,
) =>
  queryOptions<
    GetRouterConfigCatalogV1RouterConfigGetResponse,
    DefaultError,
    GetRouterConfigCatalogV1RouterConfigGetResponse,
    ReturnType<typeof getRouterConfigCatalogV1RouterConfigGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getRouterConfigCatalogV1RouterConfigGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getRouterConfigCatalogV1RouterConfigGetQueryKey(options),
  });

export const tailReplicaLogsCatalogV1PilotReplicasSlugLogsGetQueryKey = (
  options: Options<TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetData>,
) =>
  createQueryKey("tailReplicaLogsCatalogV1PilotReplicasSlugLogsGet", options);

/**
 * Tail Replica Logs
 *
 * Read tail of logs generated by replica.
 */
export const tailReplicaLogsCatalogV1PilotReplicasSlugLogsGetOptions = (
  options: Options<TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetData>,
) =>
  queryOptions<
    TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetResponse,
    TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetError,
    TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetResponse,
    ReturnType<typeof tailReplicaLogsCatalogV1PilotReplicasSlugLogsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await tailReplicaLogsCatalogV1PilotReplicasSlugLogsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: tailReplicaLogsCatalogV1PilotReplicasSlugLogsGetQueryKey(options),
  });
