import os
from enum import Enum
from pathlib import Path
from typing import Any, Callable, ClassVar, Literal, NewType, TypedDict

from jinja2 import Environment, TemplateSyntaxError, meta
from pydantic import (
    BaseModel,
    ConfigDict,
    GetCoreSchemaHandler,
    ImportString,
    SecretStr,
    field_validator,
)
from pydantic_core import core_schema

from .base_scheduler import SchedulerAdapter

ResourceName = NewType("ResourceName", str)


class HealthEndpointStatus(str, Enum):
    """
    Result from /health API check
    """

    healthy = "healthy"
    unhealthy = "unhealthy"
    unknown = "unknown"


class DeploymentHealth(str, Enum):
    """
    Aggregated deployment health
    """

    offline = "offline"  # No replicas exist / all pending
    starting = "starting"  # All replicas are placed or launching
    healthy = "healthy"  # Up at full capacity
    partial_capacity = "partial_capacity"  # Up at partial capacity
    unhealthy = "unhealthy"  # Replicas exist, but none are ready


class ClusterStatus(str, Enum):
    """
    Overall status of an HPC / Inference Cluster
    """

    up = "up"
    down = "down"
    degraded = "degraded"
    maintenance = "maintenance"
    unknown = "unknown"


class ReplicaPhase(str, Enum):
    """
    Lifecycle of a single AI model instance (replica).
    """

    # initial states
    pending = "pending"  # desired; awaiting placement (no GPUs claimed)
    placed = "placed"  # GPUs claimed on a PilotJob; not yet launched
    launching = "launching"  # control plane Popen'd it; weights loading

    # poll until ready, timeout, or exited
    ready = "ready"  # serving; registered with the router
    unhealthy = "unhealthy"  # was READY, now failing /health

    # Terminal states:
    error = "error"  # Process exited with nonzero status code
    start_timeout = "start_timeout"  # Did not become healthy within max_startup_sec
    terminating = "terminating"  # being torn down
    terminated = "terminated"  # finished tear down


class RouterParams(BaseModel):
    """
    Desired deployment routing configuration.

    Passes through to LiteLLM Router when applicable.
    """

    weight: int = 1
    rpm: int | None = None
    tpm: int | None = None
    max_parallel_requests: int | None = None
    order: int | None = None


class PilotConfig(BaseModel):
    """
    HPC Cluster-wide configuration for the pilot system.

    Controls how pilots are started and configured.
    """

    scheduler_adapter: ImportString[type[SchedulerAdapter]]
    scheduler_config: dict[str, Any] = {}

    job_walltime_min: int
    pilot_max_idle_time_min: int = 60
    max_concurrent_jobs: int = 100
    queue: str
    account: str
    scheduler_flags: str = ""
    workdir: Path
    external_port: int
    nginx_path: Path
    ip_allowlist: list[str]
    node_file_env: str
    submit_script_preamble: str
    pilot_version: str


class LoadThresholdStrategy(BaseModel):
    """
    A method for automatically scaling a PilotDeployment by tracking the average
    load (defined as number of concurrent requests) and setting the desired
    number of replicas by a ladder of thresholds.
    """

    strategy: Literal["LoadThresholdStrategy"] = "LoadThresholdStrategy"
    scale_up_interval_min: int = 2  # scale up at most once / 2 min
    scale_down_age_min: int = 120  # a started replica lives 2 hr before scale-down

    # Ordered (load_lower_bound_exclusive, num_replicas). At/below the lowest
    # threshold, scale to min_replicas.
    scaling_thresholds: list[tuple[float, int]] = [
        (0.0, 1),  # load > 0 (not idle) → 1 replica
        (10.0, 2),  # load > 120          → 2 replicas
    ]


class ScriptTemplateContext(TypedDict):
    """
    Variables made available to `PilotLaunchSpec.serve_script_template` when it
    is rendered.

    The single source of truth for what a Jinja template author may reference.
    """

    replica_name: str
    """Unique name of this replica (generated by pilot system)"""

    served_model_name: str
    """`served_model_name` from the launch spec."""

    port: int
    """TCP port the replica must listen on."""

    gpus_per_node: int
    """`gpus_per_node` from the launch spec."""

    num_nodes: int
    """`num_nodes` from the launch spec."""

    gpus_by_host: dict[str, list[str]]
    """
    GPU ids allocated to this replica, grouped by hostname. Order within each
    list is preserved from the scheduler's claim.
    """

    venv_path: str
    """`venv_path` from the launch spec"""

    weights_path: str
    """`weights_path` from the launch spec"""

    weights_cache_path: str
    """`weights_cache_path` from the launch spec"""

    env: dict[str, str]
    """
    `env` from the launch spec. Also injected into the subprocess environment,
    so most templates do not need to reference it directly.
    """

    quote: Callable[[str], str]
    """`shlex.quote`, for safely interpolating any of the above into a shell command."""


SCRIPT_TEMPLATE_VARIABLES: frozenset[str] = frozenset(
    ScriptTemplateContext.__annotations__
)


class PilotLaunchSpec(BaseModel):
    """
    Specification for launching a model replica inside of a pilot job.

    The Spec author retains full flexibility to write a bash model startup
    script in `serve_script_template`. The template must respect the port,
    served model name, and GPU resources provided as context to the script
    template.
    """

    model_config = ConfigDict(use_attribute_docstrings=True)
    served_model_name: str

    gpus_per_node: int
    num_nodes: int

    venv_path: Path
    weights_path: Path
    weights_cache_path: Path

    env: dict[str, str]

    serve_script_template: str

    max_startup_sec: int
    health_path: str | None = "/health"

    @field_validator("serve_script_template")
    @classmethod
    def _check_template_variables(cls, v: str) -> str:
        try:
            ast = Environment().parse(v)
        except TemplateSyntaxError as e:
            raise ValueError(f"serve_script_template is not valid Jinja2: {e}") from e
        used = meta.find_undeclared_variables(ast)
        unknown = used - SCRIPT_TEMPLATE_VARIABLES
        if unknown:
            raise ValueError(
                f"serve_script_template references unknown variables: "
                f"{sorted(unknown)}. Allowed: {sorted(SCRIPT_TEMPLATE_VARIABLES)}"
            )
        return v


class GpuClaim(BaseModel):
    """
    An reservation of GPUs on a host.

    Tracked by the Pilot system when placing replicas onto pilot jobs.  Included
    in each ReplicaStartRequest to start the replica on the desired GPUs.
    """

    hostname: str
    gpu_ids: list[str]


class SecretRef(str):
    """
    A pydantic field that allows secrets to be included as references to a
    remote resource in the declarative configuration.

    For example: the value SecretRef("env_var://METIS_API_KEY") is used so that the
    declarative configuration can be applied on a machine without access to the secret
    values. The gateway will resolve() the secret value just-in-time.

    Extend `_resolvers` to add support for additional Secret Vaulting strategies.
    """

    @staticmethod
    def _from_env_var(name: str) -> str:
        try:
            return os.environ[name]
        except KeyError:
            raise ValueError(f"environment variable {name!r} is not set")

    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: Any, handler: GetCoreSchemaHandler
    ) -> core_schema.CoreSchema:
        return core_schema.chain_schema(
            [
                core_schema.str_schema(),
                core_schema.no_info_plain_validator_function(cls._validate),
            ]
        )

    @classmethod
    def _validate(cls, value: str) -> "SecretRef":
        if not any(value.startswith(pfx) for pfx in cls._prefixes):
            raise ValueError(f"Secret Ref must be prefixed by one of: {cls._prefixes}")
        return cls(value)

    def resolve(self) -> SecretStr:
        scheme, sep, payload = self.partition("://")
        if sep and scheme in self._resolvers:
            return SecretStr(self._resolvers[scheme](payload))
        raise AssertionError(f"No secret resolver registered for {self}")

    _resolvers: ClassVar[dict[str, Callable[[str], str]]] = {
        "env_var": _from_env_var,
    }

    _prefixes = sorted(f"{k}://" for k in _resolvers)
