services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - inference-gateway
    networks:
      - gateway
    restart: unless-stopped

  inference-gateway:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file: &env-files
      - path: ../.env.default # common
        required: true
      - path: ../.env.compose # specific to compose stack
        required: true
      - path: ../.env.secret  # .gitignored secrets
        required: true
      - path: ../.env.prod    # optional prod overrides
        required: false
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - gateway
    restart: unless-stopped

  controller-manager:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file: *env-files
    command: [".venv/bin/python", "-m", "first_gateway.controllers.manager"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - gateway
    restart: unless-stopped

  postgres:
    image: postgres:18
    env_file: *env-files
    networks:
      - gateway
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U first_gateway" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8
    networks:
      - gateway
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "6379:6379"

networks:
  gateway:
    driver: bridge