services:
  postgres:
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql

  migration:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file:
      - path: ../.env.default # common
        required: true
      - path: ../.env.compose # specific to compose stack
        required: true
      - path: ../.env.secret  # .gitignored secrets
        required: true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: .venv/bin/alembic -c packages/gateway/first_gateway/database/alembic.ini upgrade head
    networks:
      - gateway