services:
  postgres:
    volumes:
      - postgres-dev:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U first_gateway -d first_gateway_dev" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file:
      - path: ../.env.default # common
        required: true
      - path: ../.env.compose # specific to compose stack
        required: true
      - path: ../.env.secret  # .gitignored secrets
        required: true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: .venv/bin/alembic -c packages/gateway/first_gateway/database/alembic.ini upgrade head
    networks:
      - gateway

  redis:
    volumes:
      - redis-dev:/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - gateway

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - gateway


volumes:
  grafana-storage:
  postgres-dev:
  redis-dev: