upstream app_server {
    # The internal hostname and port of the Gunicorn/Django service
    server inference-gateway:7000;
}

http {
    map $http_authorization $anon_key {
        ""      $binary_remote_addr; # Missing header -> $anon_key=IP Address
        default "";                  # Present header -> $anon_key="" (disabled)
    }

    map $http_authorization $auth_key {
        ""      "";                   # Missing header -> $auth_key="" (disabled)
        default $http_authorization;  # Present header -> $auth_key=$http_authorization
    }

    # Anon requests limited to 10/s and keyed by IP address:
    limit_req_zone $anon_key zone=anon:10m rate=10r/s;

    # Requests w/ token limited to 40/s and keyed by token:
    limit_req_zone $auth_key zone=auth:10m rate=40r/s;

    limit_req_status 429;

    server {
        listen 80;
        server_name localhost; # Or your specific domain

        # Root location - proxy all other requests to the Django app
        location / {
            limit_req zone=anon burst=20;
            limit_req zone=auth burst=80;

            proxy_pass http://app_server;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;

            # Increase timeouts for potentially long-running requests (adjust as needed)
            proxy_connect_timeout 600s;
            proxy_send_timeout 600s;
            proxy_read_timeout 600s;
            send_timeout 600s;

            # Buffer settings (adjust as needed)
            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
        }
    }

}