// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  ChatCompletionsFederatedV1ChatCompletionsPostData,
  ChatCompletionsFederatedV1ChatCompletionsPostErrors,
  ChatCompletionsFederatedV1ChatCompletionsPostResponses,
  EmbeddingsFederatedV1EmbeddingsPostData,
  EmbeddingsFederatedV1EmbeddingsPostErrors,
  EmbeddingsFederatedV1EmbeddingsPostResponses,
  GetClusterCatalogV1ClustersNameGetData,
  GetClusterCatalogV1ClustersNameGetErrors,
  GetClusterCatalogV1ClustersNameGetResponses,
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetData,
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetErrors,
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponses,
  GetRouterConfigCatalogV1RouterConfigGetData,
  GetRouterConfigCatalogV1RouterConfigGetResponses,
  GetSystemHealthCatalogV1SystemHealthGetData,
  GetSystemHealthCatalogV1SystemHealthGetResponses,
  HealthHealthGetData,
  HealthHealthGetResponses,
  ListAccessGroupsCatalogV1AccessGroupsGetData,
  ListAccessGroupsCatalogV1AccessGroupsGetResponses,
  ListClustersCatalogV1ClustersGetData,
  ListClustersCatalogV1ClustersGetResponses,
  ListModelsCatalogV1ModelsGetData,
  ListModelsCatalogV1ModelsGetResponses,
  ListPilotDeploymentsCatalogV1DeploymentsPilotGetData,
  ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponses,
  ListStaticDeploymentsCatalogV1DeploymentsStaticGetData,
  ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponses,
  ResponsesFederatedV1ResponsesPostData,
  ResponsesFederatedV1ResponsesPostErrors,
  ResponsesFederatedV1ResponsesPostResponses,
  TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetData,
  TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetErrors,
  TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetResponses,
  WhoamiWhoamiGetData,
  WhoamiWhoamiGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health
 *
 * Liveness probe
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthHealthGetData, ThrowOnError>,
): RequestResult<HealthHealthGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    HealthHealthGetResponses,
    unknown,
    ThrowOnError
  >({ url: "/health", ...options });

/**
 * Whoami
 *
 * Return the authenticated caller's identity.
 */
export const whoamiWhoamiGet = <ThrowOnError extends boolean = false>(
  options?: Options<WhoamiWhoamiGetData, ThrowOnError>,
): RequestResult<WhoamiWhoamiGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    WhoamiWhoamiGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/whoami",
    ...options,
  });

/**
 * List Access Groups
 *
 * List AccessGroups.  Admins see all; ordinary users see only the AccessGroups
 * they qualify for.
 */
export const listAccessGroupsCatalogV1AccessGroupsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListAccessGroupsCatalogV1AccessGroupsGetData, ThrowOnError>,
): RequestResult<
  ListAccessGroupsCatalogV1AccessGroupsGetResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListAccessGroupsCatalogV1AccessGroupsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/catalog/v1/access-groups",
    ...options,
  });

/**
 * List Models
 *
 * List Models.  Admins see all; ordinary users see only Models whose
 * AccessGroup grants them access.
 */
export const listModelsCatalogV1ModelsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListModelsCatalogV1ModelsGetData, ThrowOnError>,
): RequestResult<
  ListModelsCatalogV1ModelsGetResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListModelsCatalogV1ModelsGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/catalog/v1/models",
    ...options,
  });

/**
 * List Pilot Deployments
 *
 * List PilotDeployments.  Admins see all; ordinary users see only deployments
 * whose parent Model authorizes them.
 */
export const listPilotDeploymentsCatalogV1DeploymentsPilotGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListPilotDeploymentsCatalogV1DeploymentsPilotGetData,
    ThrowOnError
  >,
): RequestResult<
  ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/catalog/v1/deployments/pilot",
    ...options,
  });

/**
 * Get Pilot Deployment
 *
 * Get a single PilotDeployment with its replicas.
 */
export const getPilotDeploymentCatalogV1DeploymentsPilotNameGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetPilotDeploymentCatalogV1DeploymentsPilotNameGetData,
    ThrowOnError
  >,
): RequestResult<
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponses,
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponses,
    GetPilotDeploymentCatalogV1DeploymentsPilotNameGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/catalog/v1/deployments/pilot/{name}",
    ...options,
  });

/**
 * List Static Deployments
 *
 * List StaticDeployments.  Admins see all; ordinary users see only deployments
 * whose parent Model authorizes them.
 */
export const listStaticDeploymentsCatalogV1DeploymentsStaticGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<
    ListStaticDeploymentsCatalogV1DeploymentsStaticGetData,
    ThrowOnError
  >,
): RequestResult<
  ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/catalog/v1/deployments/static",
    ...options,
  });

/**
 * List Clusters
 *
 * List all configured Cluster resources.  Visible to all users.
 */
export const listClustersCatalogV1ClustersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ListClustersCatalogV1ClustersGetData, ThrowOnError>,
): RequestResult<
  ListClustersCatalogV1ClustersGetResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListClustersCatalogV1ClustersGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/catalog/v1/clusters",
    ...options,
  });

/**
 * Chat Completions
 */
export const chatCompletionsFederatedV1ChatCompletionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ChatCompletionsFederatedV1ChatCompletionsPostData,
    ThrowOnError
  >,
): RequestResult<
  ChatCompletionsFederatedV1ChatCompletionsPostResponses,
  ChatCompletionsFederatedV1ChatCompletionsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ChatCompletionsFederatedV1ChatCompletionsPostResponses,
    ChatCompletionsFederatedV1ChatCompletionsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/federated/v1/chat/completions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Responses
 */
export const responsesFederatedV1ResponsesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ResponsesFederatedV1ResponsesPostData, ThrowOnError>,
): RequestResult<
  ResponsesFederatedV1ResponsesPostResponses,
  ResponsesFederatedV1ResponsesPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ResponsesFederatedV1ResponsesPostResponses,
    ResponsesFederatedV1ResponsesPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/federated/v1/responses",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Embeddings
 */
export const embeddingsFederatedV1EmbeddingsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<EmbeddingsFederatedV1EmbeddingsPostData, ThrowOnError>,
): RequestResult<
  EmbeddingsFederatedV1EmbeddingsPostResponses,
  EmbeddingsFederatedV1EmbeddingsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    EmbeddingsFederatedV1EmbeddingsPostResponses,
    EmbeddingsFederatedV1EmbeddingsPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/federated/v1/embeddings",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Cluster
 *
 * Get a Cluster with its pilot jobs. Admin-only.
 */
export const getClusterCatalogV1ClustersNameGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetClusterCatalogV1ClustersNameGetData, ThrowOnError>,
): RequestResult<
  GetClusterCatalogV1ClustersNameGetResponses,
  GetClusterCatalogV1ClustersNameGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetClusterCatalogV1ClustersNameGetResponses,
    GetClusterCatalogV1ClustersNameGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/catalog/v1/clusters/{name}",
    ...options,
  });

/**
 * Get System Health
 *
 * One-glance operational snapshot: the health/state and any reconcile error
 * of every operational resource, grouped by type.  Admin-only.
 */
export const getSystemHealthCatalogV1SystemHealthGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetSystemHealthCatalogV1SystemHealthGetData, ThrowOnError>,
): RequestResult<
  GetSystemHealthCatalogV1SystemHealthGetResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetSystemHealthCatalogV1SystemHealthGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/catalog/v1/system-health",
    ...options,
  });

/**
 * Get Router Config
 */
export const getRouterConfigCatalogV1RouterConfigGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetRouterConfigCatalogV1RouterConfigGetData, ThrowOnError>,
): RequestResult<
  GetRouterConfigCatalogV1RouterConfigGetResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetRouterConfigCatalogV1RouterConfigGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/catalog/v1/router-config",
    ...options,
  });

/**
 * Tail Replica Logs
 *
 * Read tail of logs generated by replica.
 */
export const tailReplicaLogsCatalogV1PilotReplicasSlugLogsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetData,
    ThrowOnError
  >,
): RequestResult<
  TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetResponses,
  TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetResponses,
    TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/catalog/v1/pilot-replicas/{slug}/logs",
    ...options,
  });
