// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * AccessGroup
 *
 * Specifies model access permissions by user group/domain membership.
 */
export type AccessGroup = {
  /**
   * Allowed Groups
   */
  allowed_groups?: Array<string>;
  /**
   * Allowed Domains
   */
  allowed_domains?: Array<string>;
  /**
   * Kind
   */
  kind?: "AccessGroup";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * BackendConfig
 */
export type BackendConfig = {
  /**
   * Id
   */
  id: string;
  /**
   * Model Url
   */
  model_url: string;
  /**
   * Backend Model Name
   */
  backend_model_name: string;
  /**
   * Api Key
   */
  api_key: string | null;
};

/**
 * BackendRuntime
 */
export type BackendRuntime = {
  /**
   * Inflight
   */
  inflight?: number;
  /**
   * Cooldown Errors
   */
  cooldown_errors?: number;
};

/**
 * Body_apply_resources_control_v1_apply_post
 */
export type BodyApplyResourcesControlV1ApplyPost = {
  /**
   * Resources
   */
  resources: Array<ResourceManifest>;
  approved_plan: ResourceChangePlan;
};

/**
 * Body_plan_resources_control_v1_plan_post
 */
export type BodyPlanResourcesControlV1PlanPost = {
  /**
   * Resources
   */
  resources: Array<ResourceManifest>;
};

/**
 * Body_reconcile_reset_control_v1_reconcile_reset_post
 */
export type BodyReconcileResetControlV1ReconcileResetPost = {
  /**
   * Resource
   */
  resource: string;
};

/**
 * Body_set_desired_pilot_replicas_control_v1_deployments_pilot__name__desired_replicas_put
 */
export type BodySetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPut =
  {
    /**
     * Num Replicas
     */
    num_replicas: number;
  };

/**
 * ClusterDetail
 *
 * HPC Cluster information with embedded details of pilot jobs currently
 * associated with the cluster.
 */
export type ClusterDetail = {
  health_check: HealthCheckParams;
  /**
   * Maintenance Notice
   */
  maintenance_notice?: string | null;
  pilot_system?: PilotConfig | null;
  /**
   * Kind
   */
  kind?: "Cluster";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
  /**
   * Pilot Jobs
   */
  pilot_jobs: Array<PilotJob>;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * ClusterSummary
 *
 * An HPC cluster to which deployments are tied.  All StaticDeployments and
 * PilotDeployments refer to a cluster for the sake of tracking cluster
 * availability/maintenance status.
 */
export type ClusterSummary = {
  health_check: HealthCheckParams;
  /**
   * Maintenance Notice
   */
  maintenance_notice?: string | null;
  pilot_system?: PilotConfig | null;
  /**
   * Kind
   */
  kind?: "Cluster";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * ConfigVersion
 *
 * Audit history of applied configuration changes, with detailed diff.
 */
export type ConfigVersion = {
  /**
   * Uid
   */
  uid: number;
  /**
   * Applied At
   */
  applied_at: string;
  /**
   * Applied By
   */
  applied_by: string;
  /**
   * Changes
   */
  changes: {
    [key: string]: unknown;
  };
};

/**
 * ConfigVersionSummary
 *
 * Audit history of applied configuration changes.
 */
export type ConfigVersionSummary = {
  /**
   * Uid
   */
  uid: number;
  /**
   * Applied At
   */
  applied_at: string;
  /**
   * Applied By
   */
  applied_by: string;
};

/**
 * DemandSignalConfig
 *
 * Model-level config for the shared demand signal all of a model's
 * pilot deployments scale from.
 *
 * The demand signal combines in-flight request count with an estimate of
 * rejected-but-would-be-inflight demand to produce a single demand metric.
 *
 * - `reject_window_sec`: rejection rate is obtained from the rise in total
 * model rejections over this window
 * - `avg_request_duration_sec`: rejections/sec is multiplied by this duration
 * to obtain the expected number of requests that would be running if the
 * rejected traffic had been admitted.
 * - `ewma_alpha`: the autoscaler samples demand on a fixed ~10s clock and
 * smooths it into an exponentially weighted moving average
 * (`ewma = alpha*sample + (1-alpha)*ewma`).
 */
export type DemandSignalConfig = {
  /**
   * Reject Window Sec
   */
  reject_window_sec?: number;
  /**
   * Avg Request Duration Sec
   */
  avg_request_duration_sec?: number;
  /**
   * Ewma Alpha
   */
  ewma_alpha?: number;
};

/**
 * DemandThresholdStrategy
 *
 * A per-deployment policy for automatically scaling a PilotDeployment from the
 * shared per-model demand signal, setting the desired number of replicas by a
 * ladder of thresholds.
 *
 * The demand signal itself (EWMA, reject window) is configured on the parent
 * Model via `DemandSignalConfig`; this strategy only expresses how a single
 * deployment reacts to that signal.
 */
export type DemandThresholdStrategy = {
  /**
   * Strategy
   */
  strategy?: "DemandThresholdStrategy";
  /**
   * Immediate Cold Start
   */
  immediate_cold_start?: boolean;
  /**
   * Scale Down Sustain Sec
   */
  scale_down_sustain_sec?: number;
  /**
   * Scaling Thresholds
   */
  scaling_thresholds?: Array<[number, number]>;
};

/**
 * DeploymentConfig
 */
export type DeploymentConfig = {
  /**
   * Kind
   */
  kind: "pilot" | "static";
  /**
   * Name
   */
  name: string;
  router_params: RouterParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec: number;
  /**
   * Backends
   */
  backends: Array<BackendConfig>;
};

export type FieldChange = [unknown, unknown];

/**
 * GpuClaim
 *
 * An reservation of GPUs on a host.
 *
 * Tracked by the Pilot system when placing replicas onto pilot jobs.  Included
 * in each ReplicaStartRequest to start the replica on the desired GPUs.
 */
export type GpuClaim = {
  /**
   * Hostname
   */
  hostname: string;
  /**
   * Gpu Ids
   */
  gpu_ids: Array<string>;
};

/**
 * GpuInfo
 *
 * Information about a GPU resource managed by a pilot.
 */
export type GpuInfo = {
  /**
   * Index
   */
  index: string;
  /**
   * Name
   */
  name: string;
  /**
   * Memory Total Mib
   */
  memory_total_mib: number | null;
  /**
   * Memory Used Mib
   */
  memory_used_mib: number | null;
};

/**
 * HTTPMethod
 *
 * HTTP methods and descriptions
 *
 * Methods from the following RFCs are all observed:
 *
 * * RFC 7231: Hypertext Transfer Protocol (HTTP/1.1), obsoletes 2616
 * * RFC 5789: PATCH Method for HTTP
 */
export type HttpMethod =
  | "CONNECT"
  | "DELETE"
  | "GET"
  | "HEAD"
  | "OPTIONS"
  | "PATCH"
  | "POST"
  | "PUT"
  | "TRACE";

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthCheckParams
 *
 * Inputs to first_common.health.perform_health_check.
 *
 * If url is an empty string, health check is disabled.
 */
export type HealthCheckParams = {
  /**
   * Url
   */
  url: string;
  /**
   * Api Key
   */
  api_key?: string | null;
  /**
   * Connect Timeout
   */
  connect_timeout?: number;
  /**
   * Read Timeout
   */
  read_timeout?: number;
  http_method?: HttpMethod;
  /**
   * Json Body
   */
  json_body?: unknown | null;
  /**
   * Status Range
   */
  status_range?: [number, number];
  /**
   * Match Pattern
   */
  match_pattern?: string | null;
  /**
   * Attempts Per Check
   */
  attempts_per_check?: number;
  /**
   * Attempt Delay
   */
  attempt_delay?: number;
  /**
   * Debounce
   */
  debounce?: number;
};

/**
 * HealthCheckResult
 *
 * Result from /health API check
 */
export type HealthCheckResult = "healthy" | "unhealthy" | "unknown";

/**
 * HostGpus
 *
 * Information about a host and its GPU resources managed under a pilot.
 */
export type HostGpus = {
  /**
   * Hostname
   */
  hostname: string;
  /**
   * Gpus
   */
  gpus: Array<GpuInfo>;
};

/**
 * ModelConfig
 */
export type ModelConfig = {
  /**
   * Name
   */
  name: string;
  /**
   * Aliases
   */
  aliases: Array<string>;
  /**
   * Allowed Groups
   */
  allowed_groups: Array<string>;
  /**
   * Allowed Domains
   */
  allowed_domains: Array<string>;
  /**
   * Supported Endpoints
   */
  supported_endpoints: Array<string>;
  usage_limits: UsagePolicy;
  overload: OverloadPolicy;
  /**
   * Deployments
   */
  deployments: Array<DeploymentConfig>;
};

/**
 * ModelRuntime
 */
export type ModelRuntime = {
  /**
   * Total Inflight
   */
  total_inflight?: number;
  /**
   * Capacity Rejects Total
   */
  capacity_rejects_total?: number;
  /**
   * Last Capacity Reject
   */
  last_capacity_reject?: string | null;
};

/**
 * ModelSummary
 *
 * Top-level Model, which may be backed by multiple deployments.
 *
 * The model resource specifies access permissions and what gateway API
 * endpoints the model supports.
 *
 * Embeds a summary of deployments currently specified for this model.
 */
export type ModelSummary = {
  /**
   * Access Group Name
   */
  access_group_name: string;
  /**
   * Supported Endpoints
   */
  supported_endpoints: Array<string>;
  /**
   * Aliases
   */
  aliases?: Array<string>;
  usage_limits?: UsagePolicy;
  overload?: OverloadPolicy;
  demand_signal?: DemandSignalConfig;
  /**
   * Kind
   */
  kind?: "Model";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Pilot Deployments
   */
  pilot_deployments: Array<PilotDeploymentSummary>;
  /**
   * Static Deployments
   */
  static_deployments: Array<StaticDeploymentSummary>;
  runtime?: ModelRuntime;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * OpenAIChatCompletionsPayload
 */
export type OpenAiChatCompletionsPayload = {
  /**
   * Model
   */
  model: string;
  /**
   * Messages
   */
  messages: Array<unknown>;
  /**
   * Stream
   */
  stream?: boolean | null;
  [key: string]: unknown;
};

/**
 * OpenAIEmbeddingsPayload
 */
export type OpenAiEmbeddingsPayload = {
  /**
   * Model
   */
  model: string;
  /**
   * Input
   */
  input: string | Array<string> | Array<number> | Array<Array<number>>;
  [key: string]: unknown;
};

/**
 * OpenAIResponsesPayload
 */
export type OpenAiResponsesPayload = {
  /**
   * Model
   */
  model: string;
  /**
   * Input
   */
  input: unknown;
  /**
   * Stream
   */
  stream?: boolean | null;
  [key: string]: unknown;
};

/**
 * OverloadPolicy
 *
 * Retry-After parameters for overloaded models.
 */
export type OverloadPolicy = {
  /**
   * Short Retry Sec
   */
  short_retry_sec?: number;
  /**
   * Retry Jitter Percent
   */
  retry_jitter_percent?: number;
};

/**
 * PilotConfig
 *
 * HPC Cluster-wide configuration for the pilot system.
 *
 * Controls how pilots are started and configured.
 */
export type PilotConfig = {
  /**
   * Scheduler Adapter
   */
  scheduler_adapter: string;
  /**
   * Scheduler Config
   */
  scheduler_config?: {
    [key: string]: unknown;
  };
  /**
   * Job Walltime Min
   */
  job_walltime_min: number;
  /**
   * Pilot Max Idle Time Min
   */
  pilot_max_idle_time_min?: number;
  /**
   * Pilot Max Unhealthy Time Min
   */
  pilot_max_unhealthy_time_min?: number;
  /**
   * Max Concurrent Jobs
   */
  max_concurrent_jobs?: number;
  /**
   * Max Num Nodes
   */
  max_num_nodes: number;
  /**
   * Gpus Per Node
   */
  gpus_per_node: number;
  /**
   * Queue
   */
  queue: string;
  /**
   * Account
   */
  account: string;
  /**
   * Scheduler Flags
   */
  scheduler_flags?: string;
  /**
   * Workdir
   */
  workdir: string;
  /**
   * External Port
   */
  external_port: number;
  /**
   * Nginx Path
   */
  nginx_path: string;
  /**
   * Ip Allowlist
   */
  ip_allowlist: Array<string>;
  /**
   * Node File Env
   */
  node_file_env: string;
  /**
   * Submit Script Preamble
   */
  submit_script_preamble: string;
  /**
   * Pilot Path
   */
  pilot_path: string;
  /**
   * Job Name Prefix
   */
  job_name_prefix?: string;
  /**
   * Pilot Config Path
   */
  pilot_config_path?: string | null;
};

/**
 * PilotDeploymentDetail
 *
 * Pilot Deployment information, including nested replicas
 */
export type PilotDeploymentDetail = {
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  router_params: RouterParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path?: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec?: number;
  scaling_strategy?: DemandThresholdStrategy | null;
  /**
   * Min Replicas
   */
  min_replicas?: number;
  /**
   * Max Replicas
   */
  max_replicas?: number;
  launch_spec: PilotLaunchSpec;
  /**
   * Max Consecutive Launch Failures
   */
  max_consecutive_launch_failures?: number;
  /**
   * Kind
   */
  kind?: "PilotDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Desired Replicas
   */
  desired_replicas: number;
  state: PilotDeploymentState;
  /**
   * Consecutive Launch Failures
   */
  consecutive_launch_failures: number;
  /**
   * Replicas
   */
  replicas: Array<PilotReplica>;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * PilotDeploymentState
 *
 * Aggregated state of a PilotDeployment.
 *
 * Refer to aggregate_state() in pilot_replica_observer.py for the procedure to
 * calculate this state from a PilotDeployment and its Replica children.
 */
export type PilotDeploymentState =
  | "healthy"
  | "degraded"
  | "starting"
  | "stopping"
  | "failed"
  | "awaiting_capacity"
  | "offline";

/**
 * PilotDeploymentSummary
 *
 * Concise information about pilot job-based deployments, omitting any replicas
 * that may be running on the deployment currently.
 */
export type PilotDeploymentSummary = {
  /**
   * Kind
   */
  kind?: "PilotDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  router_params: RouterParams;
  /**
   * Desired Replicas
   */
  desired_replicas: number;
  state: PilotDeploymentState;
  /**
   * Consecutive Launch Failures
   */
  consecutive_launch_failures: number;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * PilotJob
 *
 * An HPC scheduler (e.g. PBS Pro) managed run of `first-pilot`.
 *
 * Submitted using the parent cluster's `pilot_system`.
 *
 * Eventually, when scheduler_state="running", the job exposes a `manager_url` which
 * provides the control API to place and manage Replicas.
 */
export type PilotJob = {
  /**
   * Kind
   */
  kind?: "PilotJob";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Scheduler Job Id
   */
  scheduler_job_id: string | null;
  /**
   * Cluster Name
   */
  cluster_name: string;
  scheduler_state: SchedulerJobState;
  /**
   * Manager Url
   */
  manager_url: string | null;
  manager_health: HealthCheckResult;
  resources: PilotResources;
  /**
   * Claimed Gpu Ids
   */
  claimed_gpu_ids: Array<[number, number]>;
  /**
   * Assigned Replicas
   */
  assigned_replicas: Array<PilotReplica>;
  /**
   * Time Started
   */
  time_started?: string | null;
  /**
   * Idle Since
   */
  idle_since?: string | null;
  /**
   * Walltime Min
   */
  walltime_min: number;
  /**
   * Num Nodes
   */
  num_nodes: number;
  /**
   * Gpus Per Node
   */
  gpus_per_node: number;
  /**
   * Deleted At
   */
  deleted_at?: string | null;
  runtime?: PilotJobRuntime | null;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * PilotJobRuntime
 */
export type PilotJobRuntime = {
  resources?: PilotResources;
};

/**
 * PilotLaunchSpec
 *
 * Specification for launching a model replica inside of a pilot job.
 *
 * The Spec author retains full flexibility to write a bash model startup
 * script in `serve_script_template`. The template must respect the port,
 * served model name, and GPU resources provided as context to the script
 * template.
 */
export type PilotLaunchSpec = {
  /**
   * Served Model Name
   */
  served_model_name: string;
  /**
   * Gpus Per Node
   */
  gpus_per_node: number;
  /**
   * Num Nodes
   */
  num_nodes: number;
  /**
   * Venv Path
   */
  venv_path: string;
  /**
   * Weights Path
   */
  weights_path: string;
  /**
   * Weights Cache Path
   */
  weights_cache_path: string;
  /**
   * Env
   */
  env: {
    [key: string]: string;
  };
  /**
   * Serve Script Template
   */
  serve_script_template: string;
  /**
   * Max Startup Sec
   */
  max_startup_sec: number;
  health_check: HealthCheckParams;
};

/**
 * PilotReplica
 *
 * A single model instance spawned by the parent PilotDeployment.
 *
 * Replicas are eventually placed onto pilot jobs where they begin executing
 * and expose a `model_url` which the gateway can reach.
 */
export type PilotReplica = {
  /**
   * Kind
   */
  kind?: "PilotReplica";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Pilot Deployment Name
   */
  pilot_deployment_name: string;
  /**
   * Pilot Job Name
   */
  pilot_job_name: string | null;
  /**
   * Claimed Gpu Ids
   */
  claimed_gpu_ids: Array<[number, number]>;
  /**
   * Resources
   */
  resources: Array<GpuClaim>;
  /**
   * Model Url
   */
  model_url: string | null;
  /**
   * Observed Served Name
   */
  observed_served_name?: string | null;
  state: ReplicaState;
  /**
   * State Message
   */
  state_message: string;
  /**
   * Started At
   */
  started_at?: string | null;
  /**
   * Stopped At
   */
  stopped_at?: string | null;
  /**
   * Deleted At
   */
  deleted_at?: string | null;
  runtime?: BackendRuntime;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * PilotResources
 *
 * Information about all hosts/GPUs managed under a pilot.
 */
export type PilotResources = {
  /**
   * Hosts
   */
  hosts?: Array<HostGpus>;
};

/**
 * PrometheusTarget
 *
 * A single target group in a Prometheus HTTP SD response.
 */
export type PrometheusTarget = {
  /**
   * Targets
   */
  targets: Array<string>;
  /**
   * Labels
   */
  labels: {
    [key: string]: string;
  };
};

/**
 * ReplicaState
 *
 * Lifecycle of a single PilotReplica model instance.
 */
export type ReplicaState =
  | "pending"
  | "placed"
  | "launching"
  | "ready"
  | "unhealthy"
  | "error"
  | "start_timeout"
  | "terminating"
  | "terminated";

/**
 * ResourceChangePlan
 *
 * A complete terraform-style change plan: what resources are being added,
 * updated, deleted relative to the previous declarative version.
 */
export type ResourceChangePlan = {
  /**
   * Previous Version
   */
  previous_version: number;
  /**
   * No Change
   */
  no_change: Array<ResourceRef>;
  /**
   * To Delete
   */
  to_delete: Array<ResourceRef>;
  /**
   * To Add
   */
  to_add: Array<ResourceManifest>;
  /**
   * To Update
   */
  to_update: Array<ResourcePatch>;
};

/**
 * ResourceHealth
 *
 * A single resource's health/state plus any reconcile error from the control
 * plane.  `status` carries the resource's health or state enum value verbatim
 * (e.g. HealthCheckResult, PilotDeploymentState, or ReplicaState); callers
 * interpret criticality per resource type.
 */
export type ResourceHealth = {
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Status
   */
  status: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
};

/**
 * ResourceManifest
 *
 * Validator of declarative YAML resource specs.
 *
 * `kind` identifies a specific ResourceSpec subclass which is used to validate
 * the content of `spec` dynamically.
 *
 * `name` is the unique identifier of each resource.  Names may contain
 * alphanumerics (a-z, A-Z, 0-9) and ._-/.  The special characters are
 * deliberately chosen so that name:slug mapping is 1:1 (bijective).
 */
export type ResourceManifest = {
  /**
   * Kind
   */
  kind: string;
  /**
   * Name
   */
  name: string;
  spec: ResourceSpec;
};

/**
 * ResourcePatch
 *
 * A resource update action: a specific (kind, name) has attributes in `patch`
 * updated.
 */
export type ResourcePatch = {
  /**
   * Kind
   */
  kind: string;
  /**
   * Name
   */
  name: string;
  /**
   * Patch
   */
  patch: {
    [key: string]: FieldChange;
  };
};

/**
 * ResourceRef
 *
 * Unique Resource Identifier
 */
export type ResourceRef = {
  /**
   * Kind
   */
  kind: string;
  /**
   * Name
   */
  name: string;
};

/**
 * ResourceSpec
 *
 * Base class for registering specs that can be referenced in a
 * `ResourceManifest`.
 */
export type ResourceSpec = {
  [key: string]: unknown;
};

/**
 * RouterConfig
 *
 * The contract between the control plane and data plane.
 *
 * The Control Plane is the sole writer of the RouterConfig: it coalesces
 * information about all model instances that are running and routeable.
 *
 * The apiserver is the sole reader of the RouterConfig: it uses this
 * live-updating configuration snapshot to route incoming traffic to model backends.
 */
export type RouterConfig = {
  /**
   * Version
   */
  version?: number;
  /**
   * Models
   */
  models?: Array<ModelConfig>;
};

/**
 * RouterParams
 *
 * Desired deployment routing configuration.
 */
export type RouterParams = {
  /**
   * Weight
   */
  weight?: number;
  /**
   * Max Backend Concurrency
   */
  max_backend_concurrency?: number;
  /**
   * Cooldown Threshold
   */
  cooldown_threshold?: number;
  /**
   * Cooldown Window Sec
   */
  cooldown_window_sec?: number;
  /**
   * Cooldown Bench Sec
   */
  cooldown_bench_sec?: number;
};

/**
 * SchedulerJobState
 *
 * Normalized Job State, from the HPC scheduler's point of view
 */
export type SchedulerJobState =
  "pending_submit" | "queued" | "starting" | "running" | "exiting" | "gone";

/**
 * StaticDeploymentDetail
 *
 * Static Deployment with backend runtime information.
 */
export type StaticDeploymentDetail = {
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  /**
   * Api Url
   */
  api_url: string;
  /**
   * Api Key
   */
  api_key?: string | null;
  /**
   * Upstream Model Name
   */
  upstream_model_name: string;
  router_params?: RouterParams;
  health_check: HealthCheckParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path?: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec?: number;
  /**
   * Kind
   */
  kind?: "StaticDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
  runtime?: BackendRuntime;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * StaticDeploymentSummary
 *
 * Concise information about StaticDeployments, where the model lifecycle is
 * externally-managed and FIRST merely proxies to a given URL.
 */
export type StaticDeploymentSummary = {
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  /**
   * Api Url
   */
  api_url: string;
  /**
   * Api Key
   */
  api_key?: string | null;
  /**
   * Upstream Model Name
   */
  upstream_model_name: string;
  router_params?: RouterParams;
  health_check: HealthCheckParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path?: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec?: number;
  /**
   * Kind
   */
  kind?: "StaticDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * SystemHealth
 *
 * One-glance operational snapshot: the health/state of every operational
 * resource, grouped by type, with reconcile errors bundled in.
 */
export type SystemHealth = {
  /**
   * Clusters
   */
  clusters: Array<ResourceHealth>;
  /**
   * Static Deployments
   */
  static_deployments: Array<ResourceHealth>;
  /**
   * Pilot Deployments
   */
  pilot_deployments: Array<ResourceHealth>;
  /**
   * Pilot Jobs
   */
  pilot_jobs: Array<ResourceHealth>;
  /**
   * Pilot Replicas
   */
  pilot_replicas: Array<ResourceHealth>;
};

/**
 * UsageLimits
 *
 * Usage rate limits.
 *
 * Tokens and requests are metered using a GCRA (leaky bucket) algorithm to
 * enable immediate bursts with smooth refill:
 * - tpm: tokens/minute steady state usage
 * - burst_tokens: Token bucket depth (max burst usage)
 * - rpm: requests/minute steady state usage
 * - burst_requests: Request bucket depth
 */
export type UsageLimits = {
  /**
   * Tpm
   */
  tpm?: number;
  /**
   * Burst Tokens
   */
  burst_tokens?: number;
  /**
   * Rpm
   */
  rpm?: number;
  /**
   * Burst Requests
   */
  burst_requests?: number;
  /**
   * Max User Concurrency
   */
  max_user_concurrency?: number;
};

/**
 * UsagePolicy
 *
 * Default usage rate limits, applied per-model x per-user.
 * Allows overriding usage limits for specific user or group IDs.
 */
export type UsagePolicy = {
  default?: UsageLimits;
  /**
   * Overrides
   */
  overrides?: {
    [key: string]: UsageLimits;
  };
};

/**
 * UserAuthEvent
 *
 * Information available after a user has successfully authenticated with the
 * apiserver.
 */
export type UserAuthEvent = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Username
   */
  username: string;
  /**
   * User Group Uuids
   */
  user_group_uuids: Array<string>;
  /**
   * Authorized Group Uuids
   */
  authorized_group_uuids?: string | null;
  /**
   * Idp Id
   */
  idp_id: string;
  /**
   * Idp Name
   */
  idp_name: string;
  /**
   * Auth Service
   */
  auth_service: string;
  /**
   * Stream
   */
  stream?: "user";
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * AccessGroup
 *
 * Specifies model access permissions by user group/domain membership.
 */
export type AccessGroupWritable = {
  /**
   * Allowed Groups
   */
  allowed_groups?: Array<string>;
  /**
   * Allowed Domains
   */
  allowed_domains?: Array<string>;
  /**
   * Kind
   */
  kind?: "AccessGroup";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
};

/**
 * ClusterDetail
 *
 * HPC Cluster information with embedded details of pilot jobs currently
 * associated with the cluster.
 */
export type ClusterDetailWritable = {
  health_check: HealthCheckParams;
  /**
   * Maintenance Notice
   */
  maintenance_notice?: string | null;
  pilot_system?: PilotConfig | null;
  /**
   * Kind
   */
  kind?: "Cluster";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
  /**
   * Pilot Jobs
   */
  pilot_jobs: Array<PilotJobWritable>;
};

/**
 * ClusterSummary
 *
 * An HPC cluster to which deployments are tied.  All StaticDeployments and
 * PilotDeployments refer to a cluster for the sake of tracking cluster
 * availability/maintenance status.
 */
export type ClusterSummaryWritable = {
  health_check: HealthCheckParams;
  /**
   * Maintenance Notice
   */
  maintenance_notice?: string | null;
  pilot_system?: PilotConfig | null;
  /**
   * Kind
   */
  kind?: "Cluster";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
};

/**
 * ModelSummary
 *
 * Top-level Model, which may be backed by multiple deployments.
 *
 * The model resource specifies access permissions and what gateway API
 * endpoints the model supports.
 *
 * Embeds a summary of deployments currently specified for this model.
 */
export type ModelSummaryWritable = {
  /**
   * Access Group Name
   */
  access_group_name: string;
  /**
   * Supported Endpoints
   */
  supported_endpoints: Array<string>;
  /**
   * Aliases
   */
  aliases?: Array<string>;
  usage_limits?: UsagePolicy;
  overload?: OverloadPolicy;
  demand_signal?: DemandSignalConfig;
  /**
   * Kind
   */
  kind?: "Model";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Pilot Deployments
   */
  pilot_deployments: Array<PilotDeploymentSummaryWritable>;
  /**
   * Static Deployments
   */
  static_deployments: Array<StaticDeploymentSummaryWritable>;
  runtime?: ModelRuntime;
};

/**
 * PilotDeploymentDetail
 *
 * Pilot Deployment information, including nested replicas
 */
export type PilotDeploymentDetailWritable = {
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  router_params: RouterParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path?: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec?: number;
  scaling_strategy?: DemandThresholdStrategy | null;
  /**
   * Min Replicas
   */
  min_replicas?: number;
  /**
   * Max Replicas
   */
  max_replicas?: number;
  launch_spec: PilotLaunchSpec;
  /**
   * Max Consecutive Launch Failures
   */
  max_consecutive_launch_failures?: number;
  /**
   * Kind
   */
  kind?: "PilotDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Desired Replicas
   */
  desired_replicas: number;
  state: PilotDeploymentState;
  /**
   * Consecutive Launch Failures
   */
  consecutive_launch_failures: number;
  /**
   * Replicas
   */
  replicas: Array<PilotReplicaWritable>;
};

/**
 * PilotDeploymentSummary
 *
 * Concise information about pilot job-based deployments, omitting any replicas
 * that may be running on the deployment currently.
 */
export type PilotDeploymentSummaryWritable = {
  /**
   * Kind
   */
  kind?: "PilotDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  router_params: RouterParams;
  /**
   * Desired Replicas
   */
  desired_replicas: number;
  state: PilotDeploymentState;
  /**
   * Consecutive Launch Failures
   */
  consecutive_launch_failures: number;
};

/**
 * PilotJob
 *
 * An HPC scheduler (e.g. PBS Pro) managed run of `first-pilot`.
 *
 * Submitted using the parent cluster's `pilot_system`.
 *
 * Eventually, when scheduler_state="running", the job exposes a `manager_url` which
 * provides the control API to place and manage Replicas.
 */
export type PilotJobWritable = {
  /**
   * Kind
   */
  kind?: "PilotJob";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Scheduler Job Id
   */
  scheduler_job_id: string | null;
  /**
   * Cluster Name
   */
  cluster_name: string;
  scheduler_state: SchedulerJobState;
  /**
   * Manager Url
   */
  manager_url: string | null;
  manager_health: HealthCheckResult;
  resources: PilotResources;
  /**
   * Claimed Gpu Ids
   */
  claimed_gpu_ids: Array<[number, number]>;
  /**
   * Assigned Replicas
   */
  assigned_replicas: Array<PilotReplicaWritable>;
  /**
   * Time Started
   */
  time_started?: string | null;
  /**
   * Idle Since
   */
  idle_since?: string | null;
  /**
   * Walltime Min
   */
  walltime_min: number;
  /**
   * Num Nodes
   */
  num_nodes: number;
  /**
   * Gpus Per Node
   */
  gpus_per_node: number;
  /**
   * Deleted At
   */
  deleted_at?: string | null;
  runtime?: PilotJobRuntime | null;
};

/**
 * PilotReplica
 *
 * A single model instance spawned by the parent PilotDeployment.
 *
 * Replicas are eventually placed onto pilot jobs where they begin executing
 * and expose a `model_url` which the gateway can reach.
 */
export type PilotReplicaWritable = {
  /**
   * Kind
   */
  kind?: "PilotReplica";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Pilot Deployment Name
   */
  pilot_deployment_name: string;
  /**
   * Pilot Job Name
   */
  pilot_job_name: string | null;
  /**
   * Claimed Gpu Ids
   */
  claimed_gpu_ids: Array<[number, number]>;
  /**
   * Resources
   */
  resources: Array<GpuClaim>;
  /**
   * Model Url
   */
  model_url: string | null;
  /**
   * Observed Served Name
   */
  observed_served_name?: string | null;
  state: ReplicaState;
  /**
   * State Message
   */
  state_message: string;
  /**
   * Started At
   */
  started_at?: string | null;
  /**
   * Stopped At
   */
  stopped_at?: string | null;
  /**
   * Deleted At
   */
  deleted_at?: string | null;
  runtime?: BackendRuntime;
};

/**
 * ResourceSpec
 *
 * Base class for registering specs that can be referenced in a
 * `ResourceManifest`.
 */
export type ResourceSpecWritable = {
  [key: string]: unknown;
};

/**
 * StaticDeploymentDetail
 *
 * Static Deployment with backend runtime information.
 */
export type StaticDeploymentDetailWritable = {
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  /**
   * Api Url
   */
  api_url: string;
  /**
   * Api Key
   */
  api_key?: string | null;
  /**
   * Upstream Model Name
   */
  upstream_model_name: string;
  router_params?: RouterParams;
  health_check: HealthCheckParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path?: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec?: number;
  /**
   * Kind
   */
  kind?: "StaticDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
  runtime?: BackendRuntime;
};

/**
 * StaticDeploymentSummary
 *
 * Concise information about StaticDeployments, where the model lifecycle is
 * externally-managed and FIRST merely proxies to a given URL.
 */
export type StaticDeploymentSummaryWritable = {
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  /**
   * Api Url
   */
  api_url: string;
  /**
   * Api Key
   */
  api_key?: string | null;
  /**
   * Upstream Model Name
   */
  upstream_model_name: string;
  router_params?: RouterParams;
  health_check: HealthCheckParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path?: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec?: number;
  /**
   * Kind
   */
  kind?: "StaticDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
};

export type HealthHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthHealthGetResponses = {
  /**
   * Response Health Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthHealthGetResponse =
  HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type PrometheusServiceDiscoveryDiscoveryV1PrometheusGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/discovery/v1/prometheus";
};

export type PrometheusServiceDiscoveryDiscoveryV1PrometheusGetResponses = {
  /**
   * Response Prometheus Service Discovery Discovery V1 Prometheus Get
   *
   * Successful Response
   */
  200: Array<PrometheusTarget>;
};

export type PrometheusServiceDiscoveryDiscoveryV1PrometheusGetResponse =
  PrometheusServiceDiscoveryDiscoveryV1PrometheusGetResponses[keyof PrometheusServiceDiscoveryDiscoveryV1PrometheusGetResponses];

export type WhoamiWhoamiGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/whoami";
};

export type WhoamiWhoamiGetResponses = {
  /**
   * Successful Response
   */
  200: UserAuthEvent;
};

export type WhoamiWhoamiGetResponse =
  WhoamiWhoamiGetResponses[keyof WhoamiWhoamiGetResponses];

export type ListAccessGroupsCatalogV1AccessGroupsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/access-groups";
};

export type ListAccessGroupsCatalogV1AccessGroupsGetResponses = {
  /**
   * Response List Access Groups Catalog V1 Access Groups Get
   *
   * Successful Response
   */
  200: Array<AccessGroup>;
};

export type ListAccessGroupsCatalogV1AccessGroupsGetResponse =
  ListAccessGroupsCatalogV1AccessGroupsGetResponses[keyof ListAccessGroupsCatalogV1AccessGroupsGetResponses];

export type ListModelsCatalogV1ModelsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/models";
};

export type ListModelsCatalogV1ModelsGetResponses = {
  /**
   * Response List Models Catalog V1 Models Get
   *
   * Successful Response
   */
  200: Array<ModelSummary>;
};

export type ListModelsCatalogV1ModelsGetResponse =
  ListModelsCatalogV1ModelsGetResponses[keyof ListModelsCatalogV1ModelsGetResponses];

export type ListPilotDeploymentsCatalogV1DeploymentsPilotGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/deployments/pilot";
};

export type ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponses = {
  /**
   * Response List Pilot Deployments Catalog V1 Deployments Pilot Get
   *
   * Successful Response
   */
  200: Array<PilotDeploymentSummary>;
};

export type ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponse =
  ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponses[keyof ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponses];

export type GetPilotDeploymentCatalogV1DeploymentsPilotNameGetData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/catalog/v1/deployments/pilot/{name}";
};

export type GetPilotDeploymentCatalogV1DeploymentsPilotNameGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPilotDeploymentCatalogV1DeploymentsPilotNameGetError =
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetErrors[keyof GetPilotDeploymentCatalogV1DeploymentsPilotNameGetErrors];

export type GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponses = {
  /**
   * Successful Response
   */
  200: PilotDeploymentDetail;
};

export type GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponse =
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponses[keyof GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponses];

export type ListStaticDeploymentsCatalogV1DeploymentsStaticGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/deployments/static";
};

export type ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponses = {
  /**
   * Response List Static Deployments Catalog V1 Deployments Static Get
   *
   * Successful Response
   */
  200: Array<StaticDeploymentDetail>;
};

export type ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponse =
  ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponses[keyof ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponses];

export type ListClustersCatalogV1ClustersGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/clusters";
};

export type ListClustersCatalogV1ClustersGetResponses = {
  /**
   * Response List Clusters Catalog V1 Clusters Get
   *
   * Successful Response
   */
  200: Array<ClusterSummary>;
};

export type ListClustersCatalogV1ClustersGetResponse =
  ListClustersCatalogV1ClustersGetResponses[keyof ListClustersCatalogV1ClustersGetResponses];

export type ChatCompletionsFederatedV1ChatCompletionsPostData = {
  body: OpenAiChatCompletionsPayload;
  path?: never;
  query?: never;
  url: "/federated/v1/chat/completions";
};

export type ChatCompletionsFederatedV1ChatCompletionsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ChatCompletionsFederatedV1ChatCompletionsPostError =
  ChatCompletionsFederatedV1ChatCompletionsPostErrors[keyof ChatCompletionsFederatedV1ChatCompletionsPostErrors];

export type ChatCompletionsFederatedV1ChatCompletionsPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ResponsesFederatedV1ResponsesPostData = {
  body: OpenAiResponsesPayload;
  path?: never;
  query?: never;
  url: "/federated/v1/responses";
};

export type ResponsesFederatedV1ResponsesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResponsesFederatedV1ResponsesPostError =
  ResponsesFederatedV1ResponsesPostErrors[keyof ResponsesFederatedV1ResponsesPostErrors];

export type ResponsesFederatedV1ResponsesPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type EmbeddingsFederatedV1EmbeddingsPostData = {
  body: OpenAiEmbeddingsPayload;
  path?: never;
  query?: never;
  url: "/federated/v1/embeddings";
};

export type EmbeddingsFederatedV1EmbeddingsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EmbeddingsFederatedV1EmbeddingsPostError =
  EmbeddingsFederatedV1EmbeddingsPostErrors[keyof EmbeddingsFederatedV1EmbeddingsPostErrors];

export type EmbeddingsFederatedV1EmbeddingsPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetClusterCatalogV1ClustersNameGetData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/catalog/v1/clusters/{name}";
};

export type GetClusterCatalogV1ClustersNameGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetClusterCatalogV1ClustersNameGetError =
  GetClusterCatalogV1ClustersNameGetErrors[keyof GetClusterCatalogV1ClustersNameGetErrors];

export type GetClusterCatalogV1ClustersNameGetResponses = {
  /**
   * Successful Response
   */
  200: ClusterDetail;
};

export type GetClusterCatalogV1ClustersNameGetResponse =
  GetClusterCatalogV1ClustersNameGetResponses[keyof GetClusterCatalogV1ClustersNameGetResponses];

export type GetSystemHealthCatalogV1SystemHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/system-health";
};

export type GetSystemHealthCatalogV1SystemHealthGetResponses = {
  /**
   * Successful Response
   */
  200: SystemHealth;
};

export type GetSystemHealthCatalogV1SystemHealthGetResponse =
  GetSystemHealthCatalogV1SystemHealthGetResponses[keyof GetSystemHealthCatalogV1SystemHealthGetResponses];

export type GetRouterConfigCatalogV1RouterConfigGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/router-config";
};

export type GetRouterConfigCatalogV1RouterConfigGetResponses = {
  /**
   * Successful Response
   */
  200: RouterConfig;
};

export type GetRouterConfigCatalogV1RouterConfigGetResponse =
  GetRouterConfigCatalogV1RouterConfigGetResponses[keyof GetRouterConfigCatalogV1RouterConfigGetResponses];

export type PlanResourcesControlV1PlanPostData = {
  body: BodyPlanResourcesControlV1PlanPost;
  path?: never;
  query?: never;
  url: "/control/v1/plan";
};

export type PlanResourcesControlV1PlanPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type PlanResourcesControlV1PlanPostError =
  PlanResourcesControlV1PlanPostErrors[keyof PlanResourcesControlV1PlanPostErrors];

export type PlanResourcesControlV1PlanPostResponses = {
  /**
   * Successful Response
   */
  200: ResourceChangePlan;
};

export type PlanResourcesControlV1PlanPostResponse =
  PlanResourcesControlV1PlanPostResponses[keyof PlanResourcesControlV1PlanPostResponses];

export type ApplyResourcesControlV1ApplyPostData = {
  body: BodyApplyResourcesControlV1ApplyPost;
  path?: never;
  query?: never;
  url: "/control/v1/apply";
};

export type ApplyResourcesControlV1ApplyPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ApplyResourcesControlV1ApplyPostError =
  ApplyResourcesControlV1ApplyPostErrors[keyof ApplyResourcesControlV1ApplyPostErrors];

export type ApplyResourcesControlV1ApplyPostResponses = {
  /**
   * Response Apply Resources Control V1 Apply Post
   *
   * Successful Response
   */
  200: ConfigVersion | null;
};

export type ApplyResourcesControlV1ApplyPostResponse =
  ApplyResourcesControlV1ApplyPostResponses[keyof ApplyResourcesControlV1ApplyPostResponses];

export type ListConfigVersionsControlV1ConfigVersionsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/control/v1/config-versions";
};

export type ListConfigVersionsControlV1ConfigVersionsGetResponses = {
  /**
   * Response List Config Versions Control V1 Config Versions Get
   *
   * Successful Response
   */
  200: Array<ConfigVersionSummary>;
};

export type ListConfigVersionsControlV1ConfigVersionsGetResponse =
  ListConfigVersionsControlV1ConfigVersionsGetResponses[keyof ListConfigVersionsControlV1ConfigVersionsGetResponses];

export type GetConfigVersionControlV1ConfigVersionsUidGetData = {
  body?: never;
  path: {
    /**
     * Uid
     */
    uid: number;
  };
  query?: never;
  url: "/control/v1/config-versions/{uid}";
};

export type GetConfigVersionControlV1ConfigVersionsUidGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetConfigVersionControlV1ConfigVersionsUidGetError =
  GetConfigVersionControlV1ConfigVersionsUidGetErrors[keyof GetConfigVersionControlV1ConfigVersionsUidGetErrors];

export type GetConfigVersionControlV1ConfigVersionsUidGetResponses = {
  /**
   * Successful Response
   */
  200: ConfigVersion;
};

export type GetConfigVersionControlV1ConfigVersionsUidGetResponse =
  GetConfigVersionControlV1ConfigVersionsUidGetResponses[keyof GetConfigVersionControlV1ConfigVersionsUidGetResponses];

export type SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutData =
  {
    body: BodySetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPut;
    path: {
      /**
       * Name
       */
      name: string;
    };
    query?: never;
    url: "/control/v1/deployments/pilot/{name}/desired-replicas";
  };

export type SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutError =
  SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutErrors[keyof SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutErrors];

export type SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutResponses =
  {
    /**
     * Successful Response
     */
    200: PilotDeploymentSummary;
  };

export type SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutResponse =
  SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutResponses[keyof SetDesiredPilotReplicasControlV1DeploymentsPilotNameDesiredReplicasPutResponses];

export type ReconcileResetControlV1ReconcileResetPostData = {
  body: BodyReconcileResetControlV1ReconcileResetPost;
  path?: never;
  query?: never;
  url: "/control/v1/reconcile-reset";
};

export type ReconcileResetControlV1ReconcileResetPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReconcileResetControlV1ReconcileResetPostError =
  ReconcileResetControlV1ReconcileResetPostErrors[keyof ReconcileResetControlV1ReconcileResetPostErrors];

export type ReconcileResetControlV1ReconcileResetPostResponses = {
  /**
   * Response Reconcile Reset Control V1 Reconcile Reset Post
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type ReconcileResetControlV1ReconcileResetPostResponse =
  ReconcileResetControlV1ReconcileResetPostResponses[keyof ReconcileResetControlV1ReconcileResetPostResponses];

export type TailReplicaLogsControlV1PilotReplicasSlugLogsGetData = {
  body?: never;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: "/control/v1/pilot-replicas/{slug}/logs";
};

export type TailReplicaLogsControlV1PilotReplicasSlugLogsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TailReplicaLogsControlV1PilotReplicasSlugLogsGetError =
  TailReplicaLogsControlV1PilotReplicasSlugLogsGetErrors[keyof TailReplicaLogsControlV1PilotReplicasSlugLogsGetErrors];

export type TailReplicaLogsControlV1PilotReplicasSlugLogsGetResponses = {
  /**
   * Response Tail Replica Logs Control V1 Pilot Replicas  Slug  Logs Get
   *
   * Successful Response
   */
  200: string;
};

export type TailReplicaLogsControlV1PilotReplicasSlugLogsGetResponse =
  TailReplicaLogsControlV1PilotReplicasSlugLogsGetResponses[keyof TailReplicaLogsControlV1PilotReplicasSlugLogsGetResponses];
