// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccessGroup
 *
 * Specifies model access permissions by user group/domain membership.
 */
export type AccessGroup = {
  /**
   * Allowed Groups
   */
  allowed_groups?: Array<string>;
  /**
   * Allowed Domains
   */
  allowed_domains?: Array<string>;
  /**
   * Kind
   */
  kind?: "AccessGroup";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * AnthropicMessagesPayload
 */
export type AnthropicMessagesPayload = {
  /**
   * Model
   */
  model: string;
  /**
   * Messages
   */
  messages: Array<unknown>;
  /**
   * System
   */
  system?: string | Array<unknown> | null;
  /**
   * Stream
   */
  stream?: boolean | null;
  /**
   * Max Tokens
   */
  max_tokens: number;
  /**
   * Tools
   */
  tools?: unknown;
  [key: string]: unknown;
};

/**
 * BackendConfig
 */
export type BackendConfig = {
  /**
   * Id
   */
  id: string;
  /**
   * Model Url
   */
  model_url: string;
  /**
   * Backend Model Name
   */
  backend_model_name: string;
  /**
   * Api Key
   */
  api_key: string | null;
};

/**
 * BackendRuntime
 */
export type BackendRuntime = {
  /**
   * Inflight
   */
  inflight?: number;
  /**
   * Cooldown Errors
   */
  cooldown_errors?: number;
};

/**
 * ClusterDetail
 *
 * HPC Cluster information with embedded details of pilot jobs currently
 * associated with the cluster.
 */
export type ClusterDetail = {
  health_check: HealthCheckParams;
  /**
   * Maintenance Notice
   */
  maintenance_notice?: string | null;
  pilot_system?: PilotConfig | null;
  /**
   * Kind
   */
  kind?: "Cluster";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
  /**
   * Pilot Jobs
   */
  pilot_jobs: Array<PilotJob>;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * ClusterEndpointSummary
 */
export type ClusterEndpointSummary = {
  /**
   * Base Url
   */
  base_url: string;
  /**
   * Frameworks
   */
  frameworks: {
    [key: string]: FrameworkSummary;
  };
};

/**
 * ClusterSummary
 *
 * An HPC cluster to which deployments are tied.  All StaticDeployments and
 * PilotDeployments refer to a cluster for the sake of tracking cluster
 * availability/maintenance status.
 */
export type ClusterSummary = {
  health_check: HealthCheckParams;
  /**
   * Maintenance Notice
   */
  maintenance_notice?: string | null;
  pilot_system?: PilotConfig | null;
  /**
   * Kind
   */
  kind?: "Cluster";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * DemandSignalConfig
 *
 * Model-level config for the shared demand signal all of a model's
 * pilot deployments scale from.
 *
 * The demand signal combines in-flight request count with an estimate of
 * rejected-but-would-be-inflight demand to produce a single demand metric.
 *
 * - `reject_window_sec`: rejection rate is obtained from the rise in total
 * model rejections over this window
 * - `avg_request_duration_sec`: rejections/sec is multiplied by this duration
 * to obtain the expected number of requests that would be running if the
 * rejected traffic had been admitted.
 * - `ewma_alpha`: the autoscaler samples demand on a fixed ~10s clock and
 * smooths it into an exponentially weighted moving average
 * (`ewma = alpha*sample + (1-alpha)*ewma`).
 */
export type DemandSignalConfig = {
  /**
   * Reject Window Sec
   */
  reject_window_sec?: number;
  /**
   * Avg Request Duration Sec
   */
  avg_request_duration_sec?: number;
  /**
   * Ewma Alpha
   */
  ewma_alpha?: number;
};

/**
 * DemandThresholdStrategy
 *
 * A per-deployment policy for automatically scaling a PilotDeployment from the
 * shared per-model demand signal, setting the desired number of replicas by a
 * ladder of thresholds.
 *
 * The demand signal itself (EWMA, reject window) is configured on the parent
 * Model via `DemandSignalConfig`; this strategy only expresses how a single
 * deployment reacts to that signal.
 */
export type DemandThresholdStrategy = {
  /**
   * Strategy
   */
  strategy?: "DemandThresholdStrategy";
  /**
   * Immediate Cold Start
   */
  immediate_cold_start?: boolean;
  /**
   * Scale Down Sustain Sec
   */
  scale_down_sustain_sec?: number;
  /**
   * Scaling Thresholds
   */
  scaling_thresholds?: Array<[number, number]>;
};

/**
 * DeploymentConfig
 */
export type DeploymentConfig = {
  /**
   * Kind
   */
  kind: "pilot" | "static";
  /**
   * Name
   */
  name: string;
  /**
   * Cluster Name
   */
  cluster_name: string;
  router_params: RouterParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec: number;
  /**
   * Backends
   */
  backends: Array<BackendConfig>;
  /**
   * Incoming
   */
  incoming?: boolean;
  /**
   * Earliest Placed At
   */
  earliest_placed_at?: string | null;
  /**
   * Last Startup Sec
   */
  last_startup_sec?: number | null;
};

/**
 * FrameworkSummary
 */
export type FrameworkSummary = {
  /**
   * Models
   */
  models: Array<string>;
  /**
   * Endpoints
   */
  endpoints: Array<string>;
};

/**
 * GenericTaskPayload
 *
 * A non-LLM task proxied verbatim to the backend's `/v1/{endpoint}`.
 *
 * The caller supplies the target `endpoint` in the body alongside `model` and
 * arbitrary extra fields (passed through untouched).  These requests are always
 * unary and estimated/actual tokens are always 0.
 */
export type GenericTaskPayload = {
  /**
   * Endpoint
   */
  endpoint: string;
  /**
   * Model
   */
  model: string;
  [key: string]: unknown;
};

/**
 * GpuClaim
 *
 * An reservation of GPUs on a host.
 *
 * Tracked by the Pilot system when placing replicas onto pilot jobs.  Included
 * in each ReplicaStartRequest to start the replica on the desired GPUs.
 */
export type GpuClaim = {
  /**
   * Hostname
   */
  hostname: string;
  /**
   * Gpu Ids
   */
  gpu_ids: Array<string>;
};

/**
 * GpuInfo
 *
 * Information about a GPU resource managed by a pilot.
 */
export type GpuInfo = {
  /**
   * Index
   */
  index: string;
  /**
   * Name
   */
  name: string;
  /**
   * Memory Total Mib
   */
  memory_total_mib: number | null;
  /**
   * Memory Used Mib
   */
  memory_used_mib: number | null;
};

/**
 * HTTPMethod
 *
 * HTTP methods and descriptions
 *
 * Methods from the following RFCs are all observed:
 *
 * * RFC 7231: Hypertext Transfer Protocol (HTTP/1.1), obsoletes 2616
 * * RFC 5789: PATCH Method for HTTP
 */
export type HttpMethod =
  | "CONNECT"
  | "DELETE"
  | "GET"
  | "HEAD"
  | "OPTIONS"
  | "PATCH"
  | "POST"
  | "PUT"
  | "TRACE";

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthCheckParams
 *
 * Inputs to first_common.health.perform_health_check.
 *
 * If url is an empty string, health check is disabled.
 */
export type HealthCheckParams = {
  /**
   * Url
   */
  url: string;
  /**
   * Api Key
   */
  api_key?: string | null;
  /**
   * Connect Timeout
   */
  connect_timeout?: number;
  /**
   * Read Timeout
   */
  read_timeout?: number;
  http_method?: HttpMethod;
  /**
   * Json Body
   */
  json_body?: unknown | null;
  /**
   * Status Range
   */
  status_range?: [number, number];
  /**
   * Match Pattern
   */
  match_pattern?: string | null;
  /**
   * Attempts Per Check
   */
  attempts_per_check?: number;
  /**
   * Attempt Delay
   */
  attempt_delay?: number;
  /**
   * Debounce
   */
  debounce?: number;
};

/**
 * HealthCheckResult
 *
 * Result from /health API check
 */
export type HealthCheckResult = "healthy" | "unhealthy" | "unknown";

/**
 * HostGpus
 *
 * Information about a host and its GPU resources managed under a pilot.
 */
export type HostGpus = {
  /**
   * Hostname
   */
  hostname: string;
  /**
   * Gpus
   */
  gpus: Array<GpuInfo>;
};

/**
 * JobInfo
 */
export type JobInfo = {
  /**
   * Models
   */
  Models: string;
  /**
   * Framework
   */
  Framework: string;
  /**
   * Cluster
   */
  Cluster: string;
  [key: string]: unknown;
};

/**
 * JobsByStatus
 */
export type JobsByStatus = {
  /**
   * Running
   */
  running?: Array<JobInfo>;
  /**
   * Queued
   */
  queued?: Array<JobInfo>;
  /**
   * Stopped
   */
  stopped?: Array<JobInfo>;
  /**
   * Others
   */
  others?: Array<JobInfo>;
  /**
   * Private Batch Running
   */
  private_batch_running?: Array<JobInfo>;
  /**
   * Private Batch Queued
   */
  private_batch_queued?: Array<JobInfo>;
  /**
   * Cluster Status
   */
  cluster_status?: {
    [key: string]: unknown;
  };
};

/**
 * LaunchSpec
 *
 * Per-deployment inputs to a `LaunchTemplate`. Null overrides inherit the
 * template's value.
 */
export type LaunchSpec = {
  /**
   * Served Model Name
   */
  served_model_name: string;
  /**
   * Gpus Per Node
   */
  gpus_per_node: number;
  /**
   * Num Nodes
   */
  num_nodes: number;
  /**
   * Parameters
   */
  parameters?: {
    [key: string]: string | number | number | null;
  };
  /**
   * Env
   */
  env?: {
    [key: string]: string;
  };
  /**
   * Max Startup Sec
   */
  max_startup_sec?: number | null;
  /**
   * Max Unhealthy Sec
   */
  max_unhealthy_sec?: number | null;
  /**
   * Pre Stop Timeout Sec
   */
  pre_stop_timeout_sec?: number | null;
  /**
   * Post Stop Timeout Sec
   */
  post_stop_timeout_sec?: number | null;
  health_check?: HealthCheckParams | null;
};

/**
 * LaunchTemplate
 *
 * Reusable, typed launch scripts shared by a family of PilotDeployments.
 */
export type LaunchTemplate = {
  /**
   * Parameters
   */
  parameters?: {
    [key: string]: ScriptParameter;
  };
  /**
   * Env
   */
  env?: {
    [key: string]: string;
  };
  /**
   * Serve Script Template
   */
  serve_script_template: string;
  /**
   * Pre Stop Script Template
   */
  pre_stop_script_template?: string | null;
  /**
   * Post Stop Script Template
   */
  post_stop_script_template?: string | null;
  /**
   * Max Startup Sec
   */
  max_startup_sec: number;
  /**
   * Max Unhealthy Sec
   */
  max_unhealthy_sec?: number | null;
  /**
   * Pre Stop Timeout Sec
   */
  pre_stop_timeout_sec?: number;
  /**
   * Post Stop Timeout Sec
   */
  post_stop_timeout_sec?: number;
  health_check: HealthCheckParams;
  /**
   * Kind
   */
  kind?: "LaunchTemplate";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * ListEndpointsResponse
 */
export type ListEndpointsResponse = {
  /**
   * Clusters
   */
  clusters: {
    [key: string]: ClusterEndpointSummary;
  };
};

/**
 * ModelConfig
 */
export type ModelConfig = {
  /**
   * Name
   */
  name: string;
  /**
   * Aliases
   */
  aliases: Array<string>;
  /**
   * Allowed Groups
   */
  allowed_groups: Array<string>;
  /**
   * Allowed Domains
   */
  allowed_domains: Array<string>;
  /**
   * Supported Endpoints
   */
  supported_endpoints: Array<string>;
  /**
   * Max Model Len
   */
  max_model_len?: number | null;
  /**
   * Created At
   */
  created_at?: string | null;
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * Capabilities
   */
  capabilities?: {
    [key: string]: unknown;
  };
  usage_limits: UsagePolicy;
  overload: OverloadPolicy;
  /**
   * Deployments
   */
  deployments: Array<DeploymentConfig>;
};

/**
 * ModelInfo
 */
export type ModelInfo = {
  /**
   * Id
   */
  id: string;
  /**
   * Type
   */
  type?: "model";
  /**
   * Created At
   */
  created_at?: string | null;
  /**
   * Display Name
   */
  display_name: string;
  /**
   * Capabilities
   */
  capabilities?: {
    [key: string]: unknown;
  };
  /**
   * Max Tokens
   */
  max_tokens?: number | null;
};

/**
 * ModelListResponse
 */
export type ModelListResponse = {
  /**
   * Data
   */
  data: Array<ModelInfo>;
};

/**
 * ModelRuntime
 */
export type ModelRuntime = {
  /**
   * Total Inflight
   */
  total_inflight?: number;
  /**
   * Capacity Rejects Total
   */
  capacity_rejects_total?: number;
  /**
   * Last Capacity Reject
   */
  last_capacity_reject?: string | null;
};

/**
 * ModelSummary
 *
 * Top-level Model, which may be backed by multiple deployments.
 *
 * The model resource specifies access permissions and what gateway API
 * endpoints the model supports.
 *
 * Embeds a summary of deployments currently specified for this model.
 */
export type ModelSummary = {
  /**
   * Access Group Name
   */
  access_group_name: string;
  /**
   * Supported Endpoints
   */
  supported_endpoints: Array<string>;
  /**
   * Aliases
   */
  aliases?: Array<string>;
  usage_limits?: UsagePolicy;
  overload?: OverloadPolicy;
  demand_signal?: DemandSignalConfig;
  /**
   * Max Model Len
   */
  max_model_len?: number | null;
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * Capabilities
   */
  capabilities?: {
    [key: string]: unknown;
  };
  /**
   * Kind
   */
  kind?: "Model";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Pilot Deployments
   */
  pilot_deployments: Array<PilotDeploymentSummary>;
  /**
   * Static Deployments
   */
  static_deployments: Array<StaticDeploymentSummary>;
  runtime?: ModelRuntime;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * OpenAIChatCompletionsPayload
 */
export type OpenAiChatCompletionsPayload = {
  /**
   * Model
   */
  model: string;
  /**
   * Messages
   */
  messages: Array<unknown>;
  /**
   * Stream
   */
  stream?: boolean | null;
  /**
   * Max Completion Tokens
   */
  max_completion_tokens?: number | null;
  /**
   * Max Tokens
   */
  max_tokens?: number | null;
  /**
   * Tools
   */
  tools?: unknown;
  [key: string]: unknown;
};

/**
 * OpenAIEmbeddingsPayload
 */
export type OpenAiEmbeddingsPayload = {
  /**
   * Model
   */
  model: string;
  /**
   * Input
   */
  input: string | Array<string> | Array<number> | Array<Array<number>>;
  [key: string]: unknown;
};

/**
 * OpenAIResponsesPayload
 */
export type OpenAiResponsesPayload = {
  /**
   * Model
   */
  model: string;
  /**
   * Input
   */
  input: unknown;
  /**
   * Stream
   */
  stream?: boolean | null;
  /**
   * Max Output Tokens
   */
  max_output_tokens?: number | null;
  /**
   * Tools
   */
  tools?: unknown;
  /**
   * Instructions
   */
  instructions?: unknown;
  [key: string]: unknown;
};

/**
 * OverloadPolicy
 *
 * Retry-After parameters for overloaded models.
 */
export type OverloadPolicy = {
  /**
   * Short Retry Sec
   */
  short_retry_sec?: number;
  /**
   * Retry Jitter Percent
   */
  retry_jitter_percent?: number;
};

/**
 * PalsDiscovery
 *
 * Discover GPUs with one labeled PALS rank per scheduler host.
 */
export type PalsDiscovery = {
  /**
   * Method
   */
  method?: "pals";
  /**
   * Launcher Path
   */
  launcher_path: string;
  /**
   * Timeout Sec
   */
  timeout_sec?: number;
};

/**
 * PilotConfig
 *
 * HPC Cluster-wide configuration for the pilot system.
 *
 * Controls how pilots are started and configured.
 */
export type PilotConfig = {
  /**
   * Scheduler Adapter
   */
  scheduler_adapter: string;
  /**
   * Scheduler Config
   */
  scheduler_config?: {
    [key: string]: unknown;
  };
  /**
   * Job Walltime Min
   */
  job_walltime_min: number;
  /**
   * Pilot Max Idle Time Min
   */
  pilot_max_idle_time_min?: number;
  /**
   * Pilot Max Unhealthy Time Min
   */
  pilot_max_unhealthy_time_min?: number;
  /**
   * Max Concurrent Jobs
   */
  max_concurrent_jobs?: number;
  /**
   * Max Num Nodes
   */
  max_num_nodes: number;
  /**
   * Gpus Per Node
   */
  gpus_per_node: number;
  /**
   * Queue
   */
  queue: string;
  /**
   * Account
   */
  account: string;
  /**
   * Scheduler Flags
   */
  scheduler_flags?: string;
  /**
   * Workdir
   */
  workdir: string;
  /**
   * External Port
   */
  external_port: number;
  /**
   * Nginx Path
   */
  nginx_path: string;
  /**
   * Ip Allowlist
   */
  ip_allowlist: Array<string>;
  /**
   * Node File Env
   */
  node_file_env: string;
  /**
   * Gpu Discovery
   */
  gpu_discovery?:
    | ({
        method: "ssh";
      } & SshDiscovery)
    | ({
        method: "pals";
      } & PalsDiscovery);
  /**
   * Submit Script Preamble
   */
  submit_script_preamble: string;
  /**
   * Pilot Path
   */
  pilot_path: string;
  /**
   * Job Name Prefix
   */
  job_name_prefix?: string;
  /**
   * Pilot Config Path
   */
  pilot_config_path?: string | null;
};

/**
 * PilotDeploymentDetail
 *
 * Pilot Deployment information, including nested replicas
 */
export type PilotDeploymentDetail = {
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  router_params: RouterParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path?: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec?: number;
  scaling_strategy?: DemandThresholdStrategy | null;
  /**
   * Min Replicas
   */
  min_replicas?: number;
  /**
   * Max Replicas
   */
  max_replicas?: number;
  /**
   * Launch Template Name
   */
  launch_template_name: string;
  launch_spec: LaunchSpec;
  /**
   * Max Consecutive Launch Failures
   */
  max_consecutive_launch_failures?: number;
  /**
   * Kind
   */
  kind?: "PilotDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Desired Replicas
   */
  desired_replicas: number;
  state: PilotDeploymentState;
  /**
   * Consecutive Launch Failures
   */
  consecutive_launch_failures: number;
  /**
   * Last Startup Sec
   */
  last_startup_sec?: number | null;
  /**
   * Replicas
   */
  replicas: Array<PilotReplica>;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * PilotDeploymentState
 *
 * Aggregated state of a PilotDeployment.
 *
 * Refer to aggregate_state() in pilot_replica_observer.py for the procedure to
 * calculate this state from a PilotDeployment and its Replica children.
 */
export type PilotDeploymentState =
  | "healthy"
  | "degraded"
  | "starting"
  | "stopping"
  | "failed"
  | "awaiting_capacity"
  | "offline";

/**
 * PilotDeploymentSummary
 *
 * Concise information about pilot job-based deployments, omitting any replicas
 * that may be running on the deployment currently.
 */
export type PilotDeploymentSummary = {
  /**
   * Kind
   */
  kind?: "PilotDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  router_params: RouterParams;
  /**
   * Desired Replicas
   */
  desired_replicas: number;
  state: PilotDeploymentState;
  /**
   * Consecutive Launch Failures
   */
  consecutive_launch_failures: number;
  /**
   * Last Startup Sec
   */
  last_startup_sec?: number | null;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * PilotJob
 *
 * An HPC scheduler (e.g. PBS Pro) managed run of `first-pilot`.
 *
 * Submitted using the parent cluster's `pilot_system`.
 *
 * Eventually, when scheduler_state="running", the job exposes a `manager_url` which
 * provides the control API to place and manage Replicas.
 */
export type PilotJob = {
  /**
   * Kind
   */
  kind?: "PilotJob";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Scheduler Job Id
   */
  scheduler_job_id: string | null;
  /**
   * Cluster Name
   */
  cluster_name: string;
  scheduler_state: SchedulerJobState;
  /**
   * Manager Url
   */
  manager_url: string | null;
  manager_health: HealthCheckResult;
  resources: PilotResources;
  /**
   * Claimed Gpu Ids
   */
  claimed_gpu_ids: Array<[number, number]>;
  /**
   * Assigned Replicas
   */
  assigned_replicas: Array<PilotReplica>;
  /**
   * Time Started
   */
  time_started?: string | null;
  /**
   * Idle Since
   */
  idle_since?: string | null;
  /**
   * Walltime Min
   */
  walltime_min: number;
  /**
   * Num Nodes
   */
  num_nodes: number;
  /**
   * Gpus Per Node
   */
  gpus_per_node: number;
  /**
   * Deleted At
   */
  deleted_at?: string | null;
  runtime?: PilotJobRuntime | null;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * PilotJobRuntime
 */
export type PilotJobRuntime = {
  resources?: PilotResources;
};

/**
 * PilotReplica
 *
 * A single model instance spawned by the parent PilotDeployment.
 *
 * Replicas are eventually placed onto pilot jobs where they begin executing
 * and expose a `model_url` which the gateway can reach.
 */
export type PilotReplica = {
  /**
   * Kind
   */
  kind?: "PilotReplica";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Pilot Deployment Name
   */
  pilot_deployment_name: string;
  /**
   * Pilot Job Name
   */
  pilot_job_name: string | null;
  /**
   * Claimed Gpu Ids
   */
  claimed_gpu_ids: Array<[number, number]>;
  /**
   * Resources
   */
  resources: Array<GpuClaim>;
  /**
   * Model Url
   */
  model_url: string | null;
  /**
   * Observed Served Name
   */
  observed_served_name?: string | null;
  state: ReplicaState;
  /**
   * State Message
   */
  state_message: string;
  /**
   * Started At
   */
  started_at?: string | null;
  /**
   * Stopped At
   */
  stopped_at?: string | null;
  /**
   * Deleted At
   */
  deleted_at?: string | null;
  runtime?: BackendRuntime;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * PilotResources
 *
 * Information about all hosts/GPUs managed under a pilot.
 */
export type PilotResources = {
  /**
   * Hosts
   */
  hosts?: Array<HostGpus>;
};

/**
 * ReplicaState
 *
 * Lifecycle of a single PilotReplica model instance.
 */
export type ReplicaState =
  | "pending"
  | "placed"
  | "launching"
  | "ready"
  | "unhealthy"
  | "error"
  | "start_timeout"
  | "terminating"
  | "terminated";

/**
 * ResourceHealth
 *
 * A single resource's health/state plus any reconcile error from the control
 * plane.  `status` carries the resource's health or state enum value verbatim
 * (e.g. HealthCheckResult, PilotDeploymentState, or ReplicaState); callers
 * interpret criticality per resource type.
 */
export type ResourceHealth = {
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Status
   */
  status: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
};

/**
 * RouterConfig
 *
 * The contract between the control plane and data plane.
 *
 * The Control Plane is the sole writer of the RouterConfig: it coalesces
 * information about all model instances that are running and routeable.
 * Pilot deployments are listed even when they have no routable backend
 * (an empty `backends` list) so that their cold-start hints are available
 * to the data plane; only static deployments are omitted when unhealthy.
 *
 * The apiserver is the sole reader of the RouterConfig: it uses this
 * live-updating configuration snapshot to route incoming traffic to model backends.
 */
export type RouterConfig = {
  /**
   * Version
   */
  version?: number;
  /**
   * Models
   */
  models?: Array<ModelConfig>;
};

/**
 * RouterParams
 *
 * Desired deployment routing configuration.
 */
export type RouterParams = {
  /**
   * Weight
   */
  weight?: number;
  /**
   * Max Backend Concurrency
   */
  max_backend_concurrency?: number;
  /**
   * Cooldown Threshold
   */
  cooldown_threshold?: number;
  /**
   * Cooldown Window Sec
   */
  cooldown_window_sec?: number;
  /**
   * Cooldown Bench Sec
   */
  cooldown_bench_sec?: number;
};

/**
 * SSHDiscovery
 *
 * Discover each host's GPUs through concurrent SSH commands.
 */
export type SshDiscovery = {
  /**
   * Method
   */
  method?: "ssh";
  /**
   * Timeout Sec
   */
  timeout_sec?: number;
};

/**
 * SchedulerJobState
 *
 * Normalized Job State, from the HPC scheduler's point of view
 */
export type SchedulerJobState =
  "pending_submit" | "queued" | "starting" | "running" | "exiting" | "gone";

/**
 * ScriptParameter
 *
 * A typed input that a `LaunchTemplate` requires from each deployment.
 */
export type ScriptParameter = {
  /**
   * Type
   */
  type: "str" | "int" | "float";
  /**
   * Required
   */
  required?: boolean;
  /**
   * Default
   */
  default?: string | number | number | null;
  /**
   * Minimum
   */
  minimum?: number | null;
  /**
   * Maximum
   */
  maximum?: number | null;
};

/**
 * StagingAreaPrepared
 */
export type StagingAreaPrepared = {
  /**
   * Collection Id
   */
  collection_id: string;
  /**
   * Path
   */
  path: string;
  /**
   * Acl Rule Id
   */
  acl_rule_id: string;
  /**
   * Principal
   */
  principal: string;
};

/**
 * StaticDeploymentDetail
 *
 * Static Deployment with backend runtime information.
 */
export type StaticDeploymentDetail = {
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  /**
   * Api Url
   */
  api_url: string;
  /**
   * Api Key
   */
  api_key?: string | null;
  /**
   * Upstream Model Name
   */
  upstream_model_name: string;
  router_params?: RouterParams;
  health_check: HealthCheckParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path?: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec?: number;
  /**
   * Kind
   */
  kind?: "StaticDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
  runtime?: BackendRuntime;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * StaticDeploymentSummary
 *
 * Concise information about StaticDeployments, where the model lifecycle is
 * externally-managed and FIRST merely proxies to a given URL.
 */
export type StaticDeploymentSummary = {
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  /**
   * Api Url
   */
  api_url: string;
  /**
   * Api Key
   */
  api_key?: string | null;
  /**
   * Upstream Model Name
   */
  upstream_model_name: string;
  router_params?: RouterParams;
  health_check: HealthCheckParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path?: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec?: number;
  /**
   * Kind
   */
  kind?: "StaticDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
  /**
   * Slug
   *
   * Case-sensitive slug, safe for use in a URL path segment.
   *
   * '/' is allowed in name but unsuitable for slugs; replace it by '~' to
   * obtain a bijective mapping (~ is disallowed in name but slug-safe).
   */
  readonly slug: string;
};

/**
 * SystemHealth
 *
 * One-glance operational snapshot: the health/state of every operational
 * resource, grouped by type, with reconcile errors bundled in.
 */
export type SystemHealth = {
  /**
   * Clusters
   */
  clusters: Array<ResourceHealth>;
  /**
   * Static Deployments
   */
  static_deployments: Array<ResourceHealth>;
  /**
   * Pilot Deployments
   */
  pilot_deployments: Array<ResourceHealth>;
  /**
   * Pilot Jobs
   */
  pilot_jobs: Array<ResourceHealth>;
  /**
   * Pilot Replicas
   */
  pilot_replicas: Array<ResourceHealth>;
};

/**
 * UsageLimits
 *
 * Usage rate limits.
 *
 * Tokens and requests are metered using a GCRA (leaky bucket) algorithm to
 * enable immediate bursts with smooth refill:
 * - tpm: tokens/minute steady state usage
 * - burst_tokens: Token bucket depth (max burst usage)
 * - rpm: requests/minute steady state usage
 * - burst_requests: Request bucket depth
 */
export type UsageLimits = {
  /**
   * Tpm
   */
  tpm?: number;
  /**
   * Burst Tokens
   */
  burst_tokens?: number;
  /**
   * Rpm
   */
  rpm?: number;
  /**
   * Burst Requests
   */
  burst_requests?: number;
  /**
   * Max User Concurrency
   */
  max_user_concurrency?: number;
};

/**
 * UsageOverride
 *
 * Override usage limits, targetting a user ID, username, or group ID.
 * Only fields that are set to an integer are overridden.
 */
export type UsageOverride = {
  /**
   * Kind
   */
  kind: "user_id" | "username" | "group_id";
  /**
   * Id
   */
  id: string;
  /**
   * Tpm
   */
  tpm?: number | null;
  /**
   * Burst Tokens
   */
  burst_tokens?: number | null;
  /**
   * Rpm
   */
  rpm?: number | null;
  /**
   * Burst Requests
   */
  burst_requests?: number | null;
  /**
   * Max User Concurrency
   */
  max_user_concurrency?: number | null;
};

/**
 * UsagePolicy
 *
 * Usage rate limits, applied per-model x per-user.
 *
 * Allows overriding usage limits for specific users and groups.  Overrides are
 * partial: only explicitly set fields are overwritten.
 *
 * Overrides are layered sequentially over the default: in case of conflicts,
 * the last override wins.
 */
export type UsagePolicy = {
  default?: UsageLimits;
  /**
   * Overrides
   */
  overrides?: Array<UsageOverride>;
};

/**
 * UserAuthEvent
 *
 * Information available after a user has successfully authenticated with the
 * apiserver.
 */
export type UserAuthEvent = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Username
   */
  username: string;
  /**
   * User Group Uuids
   */
  user_group_uuids: Array<string>;
  /**
   * Authorized Group Uuids
   */
  authorized_group_uuids?: string | null;
  /**
   * Idp Id
   */
  idp_id: string;
  /**
   * Idp Name
   */
  idp_name: string;
  /**
   * Auth Service
   */
  auth_service: string;
  /**
   * Stream
   */
  stream?: "user";
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * AccessGroup
 *
 * Specifies model access permissions by user group/domain membership.
 */
export type AccessGroupWritable = {
  /**
   * Allowed Groups
   */
  allowed_groups?: Array<string>;
  /**
   * Allowed Domains
   */
  allowed_domains?: Array<string>;
  /**
   * Kind
   */
  kind?: "AccessGroup";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
};

/**
 * ClusterDetail
 *
 * HPC Cluster information with embedded details of pilot jobs currently
 * associated with the cluster.
 */
export type ClusterDetailWritable = {
  health_check: HealthCheckParams;
  /**
   * Maintenance Notice
   */
  maintenance_notice?: string | null;
  pilot_system?: PilotConfig | null;
  /**
   * Kind
   */
  kind?: "Cluster";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
  /**
   * Pilot Jobs
   */
  pilot_jobs: Array<PilotJobWritable>;
};

/**
 * ClusterSummary
 *
 * An HPC cluster to which deployments are tied.  All StaticDeployments and
 * PilotDeployments refer to a cluster for the sake of tracking cluster
 * availability/maintenance status.
 */
export type ClusterSummaryWritable = {
  health_check: HealthCheckParams;
  /**
   * Maintenance Notice
   */
  maintenance_notice?: string | null;
  pilot_system?: PilotConfig | null;
  /**
   * Kind
   */
  kind?: "Cluster";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
};

/**
 * LaunchTemplate
 *
 * Reusable, typed launch scripts shared by a family of PilotDeployments.
 */
export type LaunchTemplateWritable = {
  /**
   * Parameters
   */
  parameters?: {
    [key: string]: ScriptParameter;
  };
  /**
   * Env
   */
  env?: {
    [key: string]: string;
  };
  /**
   * Serve Script Template
   */
  serve_script_template: string;
  /**
   * Pre Stop Script Template
   */
  pre_stop_script_template?: string | null;
  /**
   * Post Stop Script Template
   */
  post_stop_script_template?: string | null;
  /**
   * Max Startup Sec
   */
  max_startup_sec: number;
  /**
   * Max Unhealthy Sec
   */
  max_unhealthy_sec?: number | null;
  /**
   * Pre Stop Timeout Sec
   */
  pre_stop_timeout_sec?: number;
  /**
   * Post Stop Timeout Sec
   */
  post_stop_timeout_sec?: number;
  health_check: HealthCheckParams;
  /**
   * Kind
   */
  kind?: "LaunchTemplate";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
};

/**
 * ModelSummary
 *
 * Top-level Model, which may be backed by multiple deployments.
 *
 * The model resource specifies access permissions and what gateway API
 * endpoints the model supports.
 *
 * Embeds a summary of deployments currently specified for this model.
 */
export type ModelSummaryWritable = {
  /**
   * Access Group Name
   */
  access_group_name: string;
  /**
   * Supported Endpoints
   */
  supported_endpoints: Array<string>;
  /**
   * Aliases
   */
  aliases?: Array<string>;
  usage_limits?: UsagePolicy;
  overload?: OverloadPolicy;
  demand_signal?: DemandSignalConfig;
  /**
   * Max Model Len
   */
  max_model_len?: number | null;
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * Capabilities
   */
  capabilities?: {
    [key: string]: unknown;
  };
  /**
   * Kind
   */
  kind?: "Model";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Pilot Deployments
   */
  pilot_deployments: Array<PilotDeploymentSummaryWritable>;
  /**
   * Static Deployments
   */
  static_deployments: Array<StaticDeploymentSummaryWritable>;
  runtime?: ModelRuntime;
};

/**
 * PilotDeploymentDetail
 *
 * Pilot Deployment information, including nested replicas
 */
export type PilotDeploymentDetailWritable = {
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  router_params: RouterParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path?: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec?: number;
  scaling_strategy?: DemandThresholdStrategy | null;
  /**
   * Min Replicas
   */
  min_replicas?: number;
  /**
   * Max Replicas
   */
  max_replicas?: number;
  /**
   * Launch Template Name
   */
  launch_template_name: string;
  launch_spec: LaunchSpec;
  /**
   * Max Consecutive Launch Failures
   */
  max_consecutive_launch_failures?: number;
  /**
   * Kind
   */
  kind?: "PilotDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Desired Replicas
   */
  desired_replicas: number;
  state: PilotDeploymentState;
  /**
   * Consecutive Launch Failures
   */
  consecutive_launch_failures: number;
  /**
   * Last Startup Sec
   */
  last_startup_sec?: number | null;
  /**
   * Replicas
   */
  replicas: Array<PilotReplicaWritable>;
};

/**
 * PilotDeploymentSummary
 *
 * Concise information about pilot job-based deployments, omitting any replicas
 * that may be running on the deployment currently.
 */
export type PilotDeploymentSummaryWritable = {
  /**
   * Kind
   */
  kind?: "PilotDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  router_params: RouterParams;
  /**
   * Desired Replicas
   */
  desired_replicas: number;
  state: PilotDeploymentState;
  /**
   * Consecutive Launch Failures
   */
  consecutive_launch_failures: number;
  /**
   * Last Startup Sec
   */
  last_startup_sec?: number | null;
};

/**
 * PilotJob
 *
 * An HPC scheduler (e.g. PBS Pro) managed run of `first-pilot`.
 *
 * Submitted using the parent cluster's `pilot_system`.
 *
 * Eventually, when scheduler_state="running", the job exposes a `manager_url` which
 * provides the control API to place and manage Replicas.
 */
export type PilotJobWritable = {
  /**
   * Kind
   */
  kind?: "PilotJob";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Scheduler Job Id
   */
  scheduler_job_id: string | null;
  /**
   * Cluster Name
   */
  cluster_name: string;
  scheduler_state: SchedulerJobState;
  /**
   * Manager Url
   */
  manager_url: string | null;
  manager_health: HealthCheckResult;
  resources: PilotResources;
  /**
   * Claimed Gpu Ids
   */
  claimed_gpu_ids: Array<[number, number]>;
  /**
   * Assigned Replicas
   */
  assigned_replicas: Array<PilotReplicaWritable>;
  /**
   * Time Started
   */
  time_started?: string | null;
  /**
   * Idle Since
   */
  idle_since?: string | null;
  /**
   * Walltime Min
   */
  walltime_min: number;
  /**
   * Num Nodes
   */
  num_nodes: number;
  /**
   * Gpus Per Node
   */
  gpus_per_node: number;
  /**
   * Deleted At
   */
  deleted_at?: string | null;
  runtime?: PilotJobRuntime | null;
};

/**
 * PilotReplica
 *
 * A single model instance spawned by the parent PilotDeployment.
 *
 * Replicas are eventually placed onto pilot jobs where they begin executing
 * and expose a `model_url` which the gateway can reach.
 */
export type PilotReplicaWritable = {
  /**
   * Kind
   */
  kind?: "PilotReplica";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  /**
   * Pilot Deployment Name
   */
  pilot_deployment_name: string;
  /**
   * Pilot Job Name
   */
  pilot_job_name: string | null;
  /**
   * Claimed Gpu Ids
   */
  claimed_gpu_ids: Array<[number, number]>;
  /**
   * Resources
   */
  resources: Array<GpuClaim>;
  /**
   * Model Url
   */
  model_url: string | null;
  /**
   * Observed Served Name
   */
  observed_served_name?: string | null;
  state: ReplicaState;
  /**
   * State Message
   */
  state_message: string;
  /**
   * Started At
   */
  started_at?: string | null;
  /**
   * Stopped At
   */
  stopped_at?: string | null;
  /**
   * Deleted At
   */
  deleted_at?: string | null;
  runtime?: BackendRuntime;
};

/**
 * StaticDeploymentDetail
 *
 * Static Deployment with backend runtime information.
 */
export type StaticDeploymentDetailWritable = {
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  /**
   * Api Url
   */
  api_url: string;
  /**
   * Api Key
   */
  api_key?: string | null;
  /**
   * Upstream Model Name
   */
  upstream_model_name: string;
  router_params?: RouterParams;
  health_check: HealthCheckParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path?: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec?: number;
  /**
   * Kind
   */
  kind?: "StaticDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
  runtime?: BackendRuntime;
};

/**
 * StaticDeploymentSummary
 *
 * Concise information about StaticDeployments, where the model lifecycle is
 * externally-managed and FIRST merely proxies to a given URL.
 */
export type StaticDeploymentSummaryWritable = {
  /**
   * Cluster Name
   */
  cluster_name: string;
  /**
   * Model Name
   */
  model_name: string;
  /**
   * Api Url
   */
  api_url: string;
  /**
   * Api Key
   */
  api_key?: string | null;
  /**
   * Upstream Model Name
   */
  upstream_model_name: string;
  router_params?: RouterParams;
  health_check: HealthCheckParams;
  /**
   * Prometheus Metrics Path
   */
  prometheus_metrics_path?: string | null;
  /**
   * Prometheus Scrape Interval Sec
   */
  prometheus_scrape_interval_sec?: number;
  /**
   * Kind
   */
  kind?: "StaticDeployment";
  /**
   * Name
   */
  name: string;
  /**
   * Uid
   */
  uid: number;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Reconcile Failures
   */
  reconcile_failures?: number;
  /**
   * Reconcile Last Error
   */
  reconcile_last_error?: string | null;
  /**
   * Reconcile Retry At
   */
  reconcile_retry_at?: string | null;
  health: HealthCheckResult;
};

export type HealthHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthHealthGetResponses = {
  /**
   * Response Health Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthHealthGetResponse =
  HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type HealthResourceServerHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/resource_server/health";
};

export type HealthResourceServerHealthGetResponses = {
  /**
   * Response Health Resource Server Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthResourceServerHealthGetResponse =
  HealthResourceServerHealthGetResponses[keyof HealthResourceServerHealthGetResponses];

export type WhoamiWhoamiGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/whoami";
};

export type WhoamiWhoamiGetResponses = {
  /**
   * Successful Response
   */
  200: UserAuthEvent;
};

export type WhoamiWhoamiGetResponse =
  WhoamiWhoamiGetResponses[keyof WhoamiWhoamiGetResponses];

export type ListAccessGroupsCatalogV1AccessGroupsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/access-groups";
};

export type ListAccessGroupsCatalogV1AccessGroupsGetResponses = {
  /**
   * Response List Access Groups Catalog V1 Access Groups Get
   *
   * Successful Response
   */
  200: Array<AccessGroup>;
};

export type ListAccessGroupsCatalogV1AccessGroupsGetResponse =
  ListAccessGroupsCatalogV1AccessGroupsGetResponses[keyof ListAccessGroupsCatalogV1AccessGroupsGetResponses];

export type ListModelsCatalogV1ModelsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/models";
};

export type ListModelsCatalogV1ModelsGetResponses = {
  /**
   * Response List Models Catalog V1 Models Get
   *
   * Successful Response
   */
  200: Array<ModelSummary>;
};

export type ListModelsCatalogV1ModelsGetResponse =
  ListModelsCatalogV1ModelsGetResponses[keyof ListModelsCatalogV1ModelsGetResponses];

export type ListPilotDeploymentsCatalogV1DeploymentsPilotGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/deployments/pilot";
};

export type ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponses = {
  /**
   * Response List Pilot Deployments Catalog V1 Deployments Pilot Get
   *
   * Successful Response
   */
  200: Array<PilotDeploymentSummary>;
};

export type ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponse =
  ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponses[keyof ListPilotDeploymentsCatalogV1DeploymentsPilotGetResponses];

export type GetPilotDeploymentCatalogV1DeploymentsPilotNameGetData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/catalog/v1/deployments/pilot/{name}";
};

export type GetPilotDeploymentCatalogV1DeploymentsPilotNameGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPilotDeploymentCatalogV1DeploymentsPilotNameGetError =
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetErrors[keyof GetPilotDeploymentCatalogV1DeploymentsPilotNameGetErrors];

export type GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponses = {
  /**
   * Successful Response
   */
  200: PilotDeploymentDetail;
};

export type GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponse =
  GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponses[keyof GetPilotDeploymentCatalogV1DeploymentsPilotNameGetResponses];

export type ListStaticDeploymentsCatalogV1DeploymentsStaticGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/deployments/static";
};

export type ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponses = {
  /**
   * Response List Static Deployments Catalog V1 Deployments Static Get
   *
   * Successful Response
   */
  200: Array<StaticDeploymentDetail>;
};

export type ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponse =
  ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponses[keyof ListStaticDeploymentsCatalogV1DeploymentsStaticGetResponses];

export type ListClustersCatalogV1ClustersGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/clusters";
};

export type ListClustersCatalogV1ClustersGetResponses = {
  /**
   * Response List Clusters Catalog V1 Clusters Get
   *
   * Successful Response
   */
  200: Array<ClusterSummary>;
};

export type ListClustersCatalogV1ClustersGetResponse =
  ListClustersCatalogV1ClustersGetResponses[keyof ListClustersCatalogV1ClustersGetResponses];

export type ChatCompletionsFederatedV1ChatCompletionsPostData = {
  body: OpenAiChatCompletionsPayload;
  path?: never;
  query?: never;
  url: "/federated/v1/chat/completions";
};

export type ChatCompletionsFederatedV1ChatCompletionsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ChatCompletionsFederatedV1ChatCompletionsPostError =
  ChatCompletionsFederatedV1ChatCompletionsPostErrors[keyof ChatCompletionsFederatedV1ChatCompletionsPostErrors];

export type ChatCompletionsFederatedV1ChatCompletionsPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ResponsesFederatedV1ResponsesPostData = {
  body: OpenAiResponsesPayload;
  path?: never;
  query?: never;
  url: "/federated/v1/responses";
};

export type ResponsesFederatedV1ResponsesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResponsesFederatedV1ResponsesPostError =
  ResponsesFederatedV1ResponsesPostErrors[keyof ResponsesFederatedV1ResponsesPostErrors];

export type ResponsesFederatedV1ResponsesPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MessagesFederatedV1MessagesPostData = {
  body: AnthropicMessagesPayload;
  path?: never;
  query?: never;
  url: "/federated/v1/messages";
};

export type MessagesFederatedV1MessagesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MessagesFederatedV1MessagesPostError =
  MessagesFederatedV1MessagesPostErrors[keyof MessagesFederatedV1MessagesPostErrors];

export type MessagesFederatedV1MessagesPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type EmbeddingsFederatedV1EmbeddingsPostData = {
  body: OpenAiEmbeddingsPayload;
  path?: never;
  query?: never;
  url: "/federated/v1/embeddings";
};

export type EmbeddingsFederatedV1EmbeddingsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EmbeddingsFederatedV1EmbeddingsPostError =
  EmbeddingsFederatedV1EmbeddingsPostErrors[keyof EmbeddingsFederatedV1EmbeddingsPostErrors];

export type EmbeddingsFederatedV1EmbeddingsPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type TasksFederatedV1TasksPostData = {
  body: GenericTaskPayload;
  path?: never;
  query?: never;
  url: "/federated/v1/tasks";
};

export type TasksFederatedV1TasksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TasksFederatedV1TasksPostError =
  TasksFederatedV1TasksPostErrors[keyof TasksFederatedV1TasksPostErrors];

export type TasksFederatedV1TasksPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListModelsFederatedV1ModelsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/federated/v1/models";
};

export type ListModelsFederatedV1ModelsGetResponses = {
  /**
   * Successful Response
   */
  200: ModelListResponse;
};

export type ListModelsFederatedV1ModelsGetResponse =
  ListModelsFederatedV1ModelsGetResponses[keyof ListModelsFederatedV1ModelsGetResponses];

export type DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostData =
  {
    body: OpenAiChatCompletionsPayload;
    path: {
      /**
       * Deployment Slug
       */
      deployment_slug: string;
    };
    query?: never;
    url: "/deployments/{deployment_slug}/v1/chat/completions";
  };

export type DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostError =
  DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostErrors[keyof DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostErrors];

export type DeploymentChatCompletionsDeploymentsDeploymentSlugV1ChatCompletionsPostResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostData = {
  body: OpenAiResponsesPayload;
  path: {
    /**
     * Deployment Slug
     */
    deployment_slug: string;
  };
  query?: never;
  url: "/deployments/{deployment_slug}/v1/responses";
};

export type DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostError =
  DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostErrors[keyof DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostErrors];

export type DeploymentResponsesDeploymentsDeploymentSlugV1ResponsesPostResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostData = {
  body: AnthropicMessagesPayload;
  path: {
    /**
     * Deployment Slug
     */
    deployment_slug: string;
  };
  query?: never;
  url: "/deployments/{deployment_slug}/v1/messages";
};

export type DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostError =
  DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostErrors[keyof DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostErrors];

export type DeploymentMessagesDeploymentsDeploymentSlugV1MessagesPostResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostData =
  {
    body: OpenAiEmbeddingsPayload;
    path: {
      /**
       * Deployment Slug
       */
      deployment_slug: string;
    };
    query?: never;
    url: "/deployments/{deployment_slug}/v1/embeddings";
  };

export type DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostError =
  DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostErrors[keyof DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostErrors];

export type DeploymentEmbeddingsDeploymentsDeploymentSlugV1EmbeddingsPostResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type DeploymentTasksDeploymentsDeploymentSlugV1TasksPostData = {
  body: GenericTaskPayload;
  path: {
    /**
     * Deployment Slug
     */
    deployment_slug: string;
  };
  query?: never;
  url: "/deployments/{deployment_slug}/v1/tasks";
};

export type DeploymentTasksDeploymentsDeploymentSlugV1TasksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeploymentTasksDeploymentsDeploymentSlugV1TasksPostError =
  DeploymentTasksDeploymentsDeploymentSlugV1TasksPostErrors[keyof DeploymentTasksDeploymentsDeploymentSlugV1TasksPostErrors];

export type DeploymentTasksDeploymentsDeploymentSlugV1TasksPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetData = {
  body?: never;
  path: {
    /**
     * Deployment Slug
     */
    deployment_slug: string;
  };
  query?: never;
  url: "/deployments/{deployment_slug}/v1/models";
};

export type ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetError =
  ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetErrors[keyof ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetErrors];

export type ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetResponses =
  {
    /**
     * Successful Response
     */
    200: ModelListResponse;
  };

export type ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetResponse =
  ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetResponses[keyof ListDeploymentModelsDeploymentsDeploymentSlugV1ModelsGetResponses];

export type WhoamiResourceServerWhoamiGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/resource_server/whoami";
};

export type WhoamiResourceServerWhoamiGetResponses = {
  /**
   * Successful Response
   */
  200: UserAuthEvent;
};

export type WhoamiResourceServerWhoamiGetResponse =
  WhoamiResourceServerWhoamiGetResponses[keyof WhoamiResourceServerWhoamiGetResponses];

export type ListEndpointsResourceServerListEndpointsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/resource_server/list-endpoints";
};

export type ListEndpointsResourceServerListEndpointsGetResponses = {
  /**
   * Successful Response
   */
  200: ListEndpointsResponse;
};

export type ListEndpointsResourceServerListEndpointsGetResponse =
  ListEndpointsResourceServerListEndpointsGetResponses[keyof ListEndpointsResourceServerListEndpointsGetResponses];

export type ClusterJobsResourceServerClusterJobsGetData = {
  body?: never;
  path: {
    /**
     * Cluster
     */
    cluster: string;
  };
  query?: never;
  url: "/resource_server/{cluster}/jobs";
};

export type ClusterJobsResourceServerClusterJobsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClusterJobsResourceServerClusterJobsGetError =
  ClusterJobsResourceServerClusterJobsGetErrors[keyof ClusterJobsResourceServerClusterJobsGetErrors];

export type ClusterJobsResourceServerClusterJobsGetResponses = {
  /**
   * Successful Response
   */
  200: JobsByStatus;
};

export type ClusterJobsResourceServerClusterJobsGetResponse =
  ClusterJobsResourceServerClusterJobsGetResponses[keyof ClusterJobsResourceServerClusterJobsGetResponses];

export type ClusterModelsResourceServerClusterModelsGetData = {
  body?: never;
  path: {
    /**
     * Cluster
     */
    cluster: string;
  };
  query?: never;
  url: "/resource_server/{cluster}/models";
};

export type ClusterModelsResourceServerClusterModelsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ClusterModelsResourceServerClusterModelsGetError =
  ClusterModelsResourceServerClusterModelsGetErrors[keyof ClusterModelsResourceServerClusterModelsGetErrors];

export type ClusterModelsResourceServerClusterModelsGetResponses = {
  /**
   * Response Cluster Models Resource Server  Cluster  Models Get
   *
   * Successful Response
   */
  200: Array<ModelSummary>;
};

export type ClusterModelsResourceServerClusterModelsGetResponse =
  ClusterModelsResourceServerClusterModelsGetResponses[keyof ClusterModelsResourceServerClusterModelsGetResponses];

export type EnsureStagingAreaResourceServerStagingPutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/resource_server/staging";
};

export type EnsureStagingAreaResourceServerStagingPutResponses = {
  /**
   * Successful Response
   */
  200: StagingAreaPrepared;
};

export type EnsureStagingAreaResourceServerStagingPutResponse =
  EnsureStagingAreaResourceServerStagingPutResponses[keyof EnsureStagingAreaResourceServerStagingPutResponses];

export type ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostData =
  {
    body: OpenAiChatCompletionsPayload;
    path: {
      /**
       * Cluster
       */
      cluster: string;
      /**
       * Framework
       */
      framework: string;
    };
    query?: never;
    url: "/resource_server/{cluster}/{framework}/v1/chat/completions";
  };

export type ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostErrors =
  {
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostError =
  ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostErrors[keyof ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostErrors];

export type ChatCompletionsResourceServerClusterFrameworkV1ChatCompletionsPostResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type ResponsesResourceServerClusterFrameworkV1ResponsesPostData = {
  body: OpenAiResponsesPayload;
  path: {
    /**
     * Cluster
     */
    cluster: string;
    /**
     * Framework
     */
    framework: string;
  };
  query?: never;
  url: "/resource_server/{cluster}/{framework}/v1/responses";
};

export type ResponsesResourceServerClusterFrameworkV1ResponsesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResponsesResourceServerClusterFrameworkV1ResponsesPostError =
  ResponsesResourceServerClusterFrameworkV1ResponsesPostErrors[keyof ResponsesResourceServerClusterFrameworkV1ResponsesPostErrors];

export type ResponsesResourceServerClusterFrameworkV1ResponsesPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type MessagesResourceServerClusterFrameworkV1MessagesPostData = {
  body: AnthropicMessagesPayload;
  path: {
    /**
     * Cluster
     */
    cluster: string;
    /**
     * Framework
     */
    framework: string;
  };
  query?: never;
  url: "/resource_server/{cluster}/{framework}/v1/messages";
};

export type MessagesResourceServerClusterFrameworkV1MessagesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MessagesResourceServerClusterFrameworkV1MessagesPostError =
  MessagesResourceServerClusterFrameworkV1MessagesPostErrors[keyof MessagesResourceServerClusterFrameworkV1MessagesPostErrors];

export type MessagesResourceServerClusterFrameworkV1MessagesPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostData = {
  body: OpenAiEmbeddingsPayload;
  path: {
    /**
     * Cluster
     */
    cluster: string;
    /**
     * Framework
     */
    framework: string;
  };
  query?: never;
  url: "/resource_server/{cluster}/{framework}/v1/embeddings";
};

export type EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostError =
  EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostErrors[keyof EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostErrors];

export type EmbeddingsResourceServerClusterFrameworkV1EmbeddingsPostResponses =
  {
    /**
     * Successful Response
     */
    200: unknown;
  };

export type ListLaunchTemplatesCatalogV1LaunchTemplatesGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/launch-templates";
};

export type ListLaunchTemplatesCatalogV1LaunchTemplatesGetResponses = {
  /**
   * Response List Launch Templates Catalog V1 Launch Templates Get
   *
   * Successful Response
   */
  200: Array<LaunchTemplate>;
};

export type ListLaunchTemplatesCatalogV1LaunchTemplatesGetResponse =
  ListLaunchTemplatesCatalogV1LaunchTemplatesGetResponses[keyof ListLaunchTemplatesCatalogV1LaunchTemplatesGetResponses];

export type GetClusterCatalogV1ClustersNameGetData = {
  body?: never;
  path: {
    /**
     * Name
     */
    name: string;
  };
  query?: never;
  url: "/catalog/v1/clusters/{name}";
};

export type GetClusterCatalogV1ClustersNameGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetClusterCatalogV1ClustersNameGetError =
  GetClusterCatalogV1ClustersNameGetErrors[keyof GetClusterCatalogV1ClustersNameGetErrors];

export type GetClusterCatalogV1ClustersNameGetResponses = {
  /**
   * Successful Response
   */
  200: ClusterDetail;
};

export type GetClusterCatalogV1ClustersNameGetResponse =
  GetClusterCatalogV1ClustersNameGetResponses[keyof GetClusterCatalogV1ClustersNameGetResponses];

export type GetSystemHealthCatalogV1SystemHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/system-health";
};

export type GetSystemHealthCatalogV1SystemHealthGetResponses = {
  /**
   * Successful Response
   */
  200: SystemHealth;
};

export type GetSystemHealthCatalogV1SystemHealthGetResponse =
  GetSystemHealthCatalogV1SystemHealthGetResponses[keyof GetSystemHealthCatalogV1SystemHealthGetResponses];

export type GetRouterConfigCatalogV1RouterConfigGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/catalog/v1/router-config";
};

export type GetRouterConfigCatalogV1RouterConfigGetResponses = {
  /**
   * Successful Response
   */
  200: RouterConfig;
};

export type GetRouterConfigCatalogV1RouterConfigGetResponse =
  GetRouterConfigCatalogV1RouterConfigGetResponses[keyof GetRouterConfigCatalogV1RouterConfigGetResponses];

export type TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetData = {
  body?: never;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: "/catalog/v1/pilot-replicas/{slug}/logs";
};

export type TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetError =
  TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetErrors[keyof TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetErrors];

export type TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetResponses = {
  /**
   * Response Tail Replica Logs Catalog V1 Pilot Replicas  Slug  Logs Get
   *
   * Successful Response
   */
  200: string;
};

export type TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetResponse =
  TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetResponses[keyof TailReplicaLogsCatalogV1PilotReplicasSlugLogsGetResponses];
